### ISSUE TITLE
prometheus的作用

### ISSUE THREAD

**Issue by WWarrenFly** [rootsongjc/kubernetes-handbook#105]
学习了你的安装prometheus的过程，但是在过程中，未提及prometheus.yml的使用，而且在prometheus-monitoring.yaml中配置的名为prometheus-core的configmap和prometheus.yml中的不太一样。请问哪个是正确的配置？

**Comment by rootsongjc** [comment]
@WWarrenFly 这个配置本身有一定问题，暂时还没解决，如果你有解决方案，欢迎提PR。
