### ISSUE TITLE
部署etcd 不能启动节点

### ISSUE THREAD

**Issue by mxg1991** [rootsongjc/kubernetes-handbook#107]
## 环境
centos7.3
**版本和配置信息**
version:3.2.13

[root@K8S-node01 ~]# cat /etc/etcd/etcd.conf 

```
# [member]
ETCD_NAME=infra1
ETCD_DATA_DIR="/var/lib/etcd"
ETCD_LISTEN_PEER_URLS="https://10.218.34.109:2380"
ETCD_LISTEN_CLIENT_URLS="https://10.218.34.109:2379"
#[cluster]
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://10.218.34.109:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_ADVERTISE_CLIENT_URLS="https://10.218.34.109:2379"

[root@K8S-node01 ~]# cat /usr/lib/systemd/system/etcd.service 
[Unit]
Description=Etcd Server
After=network.target
After=network-online.target
Wants=network-online.target
Documentation=https://github.com/coreos
[Service]
Type=notify
WorkingDirectory=/var/lib/etcd/
EnvironmentFile=-/etc/etcd/etcd.conf
ExecStart=/usr/local/bin/etcd \
--name ${ETCD_NAME} \
--cert-file=/etc/kubernetes/ssl/kubernetes.pem \
--key-file=/etc/kubernetes/ssl/kubernetes-key.pem \
--peer-cert-file=/etc/kubernetes/ssl/kubernetes.pem \
--peer-key-file=/etc/kubernetes/ssl/kubernetes-key.pem \
--trusted-ca-file=/etc/kubernetes/ssl/ca.pem \
--peer-trusted-ca-file=/etc/kubernetes/ssl/ca.pem \
--initial-advertise-peer-urls ${ETCD_INITIAL_ADVERTISE_PEER_URLS} \
--listen-peer-urls ${ETCD_LISTEN_PEER_URLS} \
--listen-client-urls ${ETCD_LISTEN_CLIENT_URLS},http://127.0.0.1:2379 \
--advertise-client-urls ${ETCD_ADVERTISE_CLIENT_URLS} \
--initial-cluster-token ${ETCD_INITIAL_CLUSTER_TOKEN} \
--initial-cluster infra1=https://10.218.34.109:2380,infra2=https://10.218.34.110:2380,infra3=https://10.218.34.111:2380 \
--initial-cluster-state new \
--data-dir=${ETCD_DATA_DIR}
Restart=on-failure
RestartSec=5
LimitNOFILE=65536
[Install]
WantedBy=multi-user.target
```

- kubernetes版本：
- docker版本：1.13.1
- 网络插件：
- 存储类型：

## 操作
systemctl start etcd 
**导致该问题的操作或现象**

## 日志

```
[root@K8S-node01 ~]# systemctl start etcd
Job for etcd.service failed because a timeout was exceeded. See "systemctl status etcd.service" and "journalctl -xe" for details.
[root@K8S-node01 ~]# journalctl -xe
Jan 12 09:02:10 K8S-node01 etcd[10077]: member dir = /var/lib/etcd/member
Jan 12 09:02:10 K8S-node01 etcd[10077]: heartbeat = 100ms
Jan 12 09:02:10 K8S-node01 etcd[10077]: election = 1000ms
Jan 12 09:02:10 K8S-node01 etcd[10077]: snapshot count = 100000
Jan 12 09:02:10 K8S-node01 etcd[10077]: advertise client URLs = https://10.218.34.109:2379
Jan 12 09:02:10 K8S-node01 etcd[10077]: restarting member 118a3396af982745 in cluster e2fb58400d740b4c at commit index 2
Jan 12 09:02:10 K8S-node01 etcd[10077]: 118a3396af982745 became follower at term 46946
Jan 12 09:02:10 K8S-node01 etcd[10077]: newRaft 118a3396af982745 [peers: [], term: 46946, commit: 2, applied: 0, lastindex: 2, lastt
Jan 12 09:02:10 K8S-node01 etcd[10077]: simple token is not cryptographically signed
Jan 12 09:02:10 K8S-node01 etcd[10077]: starting server... [version: 3.2.13, cluster version: to_be_decided]
Jan 12 09:02:10 K8S-node01 etcd[10077]: added member 118a3396af982745 [https://10.218.34.109:2380] to cluster e2fb58400d740b4c
Jan 12 09:02:10 K8S-node01 etcd[10077]: added member ab75790c89b0c5f4 [https://10.218.34.110:2380] to cluster e2fb58400d740b4c
Jan 12 09:02:10 K8S-node01 etcd[10077]: starting peer ab75790c89b0c5f4...
Jan 12 09:02:10 K8S-node01 etcd[10077]: started HTTP pipelining with peer ab75790c89b0c5f4
Jan 12 09:02:10 K8S-node01 etcd[10077]: ClientTLS: cert = /etc/kubernetes/ssl/kubernetes.pem, key = /etc/kubernetes/ssl/kubernetes-k
Jan 12 09:02:10 K8S-node01 etcd[10077]: started streaming with peer ab75790c89b0c5f4 (writer)
Jan 12 09:02:10 K8S-node01 etcd[10077]: started streaming with peer ab75790c89b0c5f4 (writer)
Jan 12 09:02:10 K8S-node01 etcd[10077]: started peer ab75790c89b0c5f4
Jan 12 09:02:10 K8S-node01 etcd[10077]: added peer ab75790c89b0c5f4
Jan 12 09:02:10 K8S-node01 etcd[10077]: started streaming with peer ab75790c89b0c5f4 (stream MsgApp v2 reader)
Jan 12 09:02:10 K8S-node01 etcd[10077]: started streaming with peer ab75790c89b0c5f4 (stream Message reader)
Jan 12 09:02:10 K8S-node01 etcd[10077]: 118a3396af982745 is starting a new election at term 46946
Jan 12 09:02:10 K8S-node01 etcd[10077]: 118a3396af982745 became candidate at term 46947
Jan 12 09:02:10 K8S-node01 etcd[10077]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 46947
Jan 12 09:02:10 K8S-node01 etcd[10077]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 469
Jan 12 09:02:11 K8S-node01 etcd[10077]: 118a3396af982745 is starting a new election at term 46947
Jan 12 09:02:11 K8S-node01 etcd[10077]: 118a3396af982745 became candidate at term 46948
Jan 12 09:02:11 K8S-node01 etcd[10077]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 46948
Jan 12 09:02:11 K8S-node01 etcd[10077]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 469
Jan 12 09:02:13 K8S-node01 etcd[10077]: 118a3396af982745 is starting a new election at term 46948
Jan 12 09:02:13 K8S-node01 etcd[10077]: 118a3396af982745 became candidate at term 46949
Jan 12 09:02:13 K8S-node01 etcd[10077]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 46949
Jan 12 09:02:13 K8S-node01 etcd[10077]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 469
Jan 12 09:02:14 K8S-node01 etcd[10077]: 118a3396af982745 is starting a new election at term 46949
Jan 12 09:02:14 K8S-node01 etcd[10077]: 118a3396af982745 became candidate at term 46950
Jan 12 09:02:14 K8S-node01 etcd[10077]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 46950
Jan 12 09:02:14 K8S-node01 etcd[10077]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 469
Jan 12 09:02:15 K8S-node01 etcd[10077]: health check for peer ab75790c89b0c5f4 could not connect: <nil>
Jan 12 09:02:16 K8S-node01 etcd[10077]: 118a3396af982745 is starting a new election at term 46950
Jan 12 09:02:16 K8S-node01 etcd[10077]: 118a3396af982745 became candidate at term 46951
Jan 12 09:02:16 K8S-node01 etcd[10077]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 46951
Jan 12 09:02:16 K8S-node01 etcd[10077]: 118a3396af982745 [logterm: 1, index: 2
```

**日志或报错信息**

```
[root@K8S-node01 ~]#  systemctl status etcd.service
â— etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: activating (start) since Fri 2018-01-12 09:13:18 CST; 26s ago
     Docs: https://github.com/coreos
 Main PID: 10188 (etcd)
   Memory: 10.6M
   CGroup: /system.slice/etcd.service
           â””â”€10188 /usr/local/bin/etcd --name infra1 --cert-file=/etc/kubernetes/ssl/kubernetes.pem --key-file=/etc/kubernetes/ss...

Jan 12 09:13:41 K8S-node01 etcd[10188]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 a...m 47398
Jan 12 09:13:43 K8S-node01 etcd[10188]: 118a3396af982745 is starting a new election at term 47398
Jan 12 09:13:43 K8S-node01 etcd[10188]: 118a3396af982745 became candidate at term 47399
Jan 12 09:13:43 K8S-node01 etcd[10188]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 47399
Jan 12 09:13:43 K8S-node01 etcd[10188]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 a...m 47399
Jan 12 09:13:44 K8S-node01 etcd[10188]: health check for peer ab75790c89b0c5f4 could not connect: dial tcp 10.218.34.110:2...timeout
Jan 12 09:13:44 K8S-node01 etcd[10188]: 118a3396af982745 is starting a new election at term 47399
Jan 12 09:13:44 K8S-node01 etcd[10188]: 118a3396af982745 became candidate at term 47400
Jan 12 09:13:44 K8S-node01 etcd[10188]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 47400
Jan 12 09:13:44 K8S-node01 etcd[10188]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 a...m 47400
```

**Comment by rootsongjc** [comment]
查看下etcd的详细日志
```
journalctl -xe -u etcd
```

**Comment by mxg1991** [comment]
journalctl -xe -u etcd
Jan 12 10:26:48 K8S-node01 etcd[11456]: ClientTLS: cert = /etc/kubernetes/ssl/kubernetes.pem, key = /etc/kubernetes/ssl/kubernetes-k
Jan 12 10:26:48 K8S-node01 etcd[11456]: started streaming with peer ab75790c89b0c5f4 (writer)
Jan 12 10:26:48 K8S-node01 etcd[11456]: started streaming with peer ab75790c89b0c5f4 (writer)
Jan 12 10:26:48 K8S-node01 etcd[11456]: started peer ab75790c89b0c5f4
Jan 12 10:26:48 K8S-node01 etcd[11456]: added peer ab75790c89b0c5f4
Jan 12 10:26:48 K8S-node01 etcd[11456]: started streaming with peer ab75790c89b0c5f4 (stream MsgApp v2 reader)
Jan 12 10:26:48 K8S-node01 etcd[11456]: started streaming with peer ab75790c89b0c5f4 (stream Message reader)
Jan 12 10:26:49 K8S-node01 etcd[11456]: 118a3396af982745 is starting a new election at term 50023
Jan 12 10:26:49 K8S-node01 etcd[11456]: 118a3396af982745 became candidate at term 50024
Jan 12 10:26:49 K8S-node01 etcd[11456]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 50024
Jan 12 10:26:49 K8S-node01 etcd[11456]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 500
Jan 12 10:26:51 K8S-node01 etcd[11456]: 118a3396af982745 is starting a new election at term 50024
Jan 12 10:26:51 K8S-node01 etcd[11456]: 118a3396af982745 became candidate at term 50025
Jan 12 10:26:51 K8S-node01 etcd[11456]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 50025
Jan 12 10:26:51 K8S-node01 etcd[11456]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 500
Jan 12 10:26:52 K8S-node01 etcd[11456]: 118a3396af982745 is starting a new election at term 50025
Jan 12 10:26:52 K8S-node01 etcd[11456]: 118a3396af982745 became candidate at term 50026
Jan 12 10:26:52 K8S-node01 etcd[11456]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 50026
Jan 12 10:26:52 K8S-node01 etcd[11456]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 500
Jan 12 10:26:53 K8S-node01 etcd[11456]: health check for peer ab75790c89b0c5f4 could not connect: <nil>
Jan 12 10:26:54 K8S-node01 etcd[11456]: 118a3396af982745 is starting a new election at term 50026
Jan 12 10:26:54 K8S-node01 etcd[11456]: 118a3396af982745 became candidate at term 50027
Jan 12 10:26:54 K8S-node01 etcd[11456]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 50027
Jan 12 10:26:54 K8S-node01 etcd[11456]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 500
Jan 12 10:26:55 K8S-node01 etcd[11456]: publish error: etcdserver: request timed out
Jan 12 10:26:56 K8S-node01 etcd[11456]: 118a3396af982745 is starting a new election at term 50027
Jan 12 10:26:56 K8S-node01 etcd[11456]: 118a3396af982745 became candidate at term 50028
Jan 12 10:26:56 K8S-node01 etcd[11456]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 50028
Jan 12 10:26:56 K8S-node01 etcd[11456]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 500
Jan 12 10:26:57 K8S-node01 etcd[11456]: 118a3396af982745 is starting a new election at term 50028
Jan 12 10:26:57 K8S-node01 etcd[11456]: 118a3396af982745 became candidate at term 50029
Jan 12 10:26:57 K8S-node01 etcd[11456]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 50029
Jan 12 10:26:57 K8S-node01 etcd[11456]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 500
Jan 12 10:26:58 K8S-node01 etcd[11456]: 118a3396af982745 is starting a new election at term 50029
Jan 12 10:26:58 K8S-node01 etcd[11456]: 118a3396af982745 became candidate at term 50030
Jan 12 10:26:58 K8S-node01 etcd[11456]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 50030
Jan 12 10:26:58 K8S-node01 etcd[11456]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 500
Jan 12 10:26:58 K8S-node01 etcd[11456]: health check for peer ab75790c89b0c5f4 could not connect: dial tcp 10.218.34.110:2380: i/o t
Jan 12 10:26:59 K8S-node01 etcd[11456]: 118a3396af982745 is starting a new election at term 50030
Jan 12 10:26:59 K8S-node01 etcd[11456]: 118a3396af982745 became candidate at term 50031
Jan 12 10:26:59 K8S-node01 etcd[11456]: 118a3396af982745 received MsgVoteResp from 118a3396af982745 at term 50031
Jan 12 10:26:59 K8S-node01 etcd[11456]: 118a3396af982745 [logterm: 1, index: 2] sent MsgVote request to ab75790c89b0c5f4 at term 500
lines 996-1037/1037 (END)

**Comment by mxg1991** [comment]
是不是网络配制有问题

**Comment by rootsongjc** [comment]
你的etcd是直接在宿主机上部署的吧，只要宿主机之间的网络通就可以了。

**Comment by mxg1991** [comment]
宿主机之间都可以PING通，还是启动失败，从日志看有可能是什么原因呢，防火墙也关了

**Comment by rootsongjc** [comment]
日志里报错的
```
health check for peer ab75790c89b0c5f4 could not connect: dial tcp 10.218.34.110:2380: i/o t
```
那个IP和端口`telnet`通吗？

**Comment by mxg1991** [comment]
上面没有telnet，ssh是可以通的，
 health check for peer ab75790c89b0c5f4 could not connect: <nil>
publish error: etcdserver: request timed out
health check for peer ab75790c89b0c5f4 could not connect: dial tcp 10.218.34.110:2380: i/o
一共有三处错误，ab75790c89b0c5f4应该是本机吧

**Comment by mxg1991** [comment]
seLinux已经disable，我的环境是内网虚拟机。是不是配制文件写错了。https需要改成http么

**Comment by Lynzabo** [comment]
需要修改防火墙，开放2379/2380端口。或者直接关闭防火墙。

**Comment by mxg1991** [comment]
@Lynzabo 谢谢，是否防火墙的问题，关闭了默认防火墙就好了
