### ISSUE TITLE
SUMMARY.md中 1.1 和2.2.1引用相同的文件,造成gitbook在阅读完2.2.1章节后,点击 > 时跳转到 1.2章节

### ISSUE THREAD

**Issue by jschunlei** [rootsongjc/kubernetes-handbook#11]
```
- [1. Kubernetes简介](introduction/index.md)
  - [1.1 核心概念](introduction/concepts.md)

- [2. 核心原理](architecture/index.md)
  - [2.1 设计理念](architecture/concepts.md)
  - [2.2 主要概念](architecture/objects.md)
    - [2.2.1 Pod, Service, Namespace和Node](introduction/concepts.md)

```
SUMMARY.md中 1.1 和2.2.1引用相同的文件,造成gitbook在阅读完2.2.1章节后,点击  `>` 按钮时跳转到 1.2章节

## PS
architecture/Service.md中
1. 
另外，也可以讲已有的服务  ==>  另外，也可以`将`已有的服务
2. 
－ 只支持4层负载均衡，没有7层功能
－ 对外访问的时候，NodePort类型需要在外部搭建额外的负载均衡，而LoadBalancer要求

上面两行中的 －是中文符,应该使用英文符的 -

**觉得文章写得很好,所以想把这些小瑕疵都除去,见谅**

**Comment by rootsongjc** [comment]
多谢指正，已修复。
PS. Pod, Service, Namespace和Node已去掉，将分别创建Pod、Namespace和Node的文章。
