### ISSUE TITLE
traefik-ingress-installation, 文件名称更新

### ISSUE THREAD

**Issue by tomtsang** [rootsongjc/kubernetes-handbook#114]
我已提 PR 了...
我一定要提成功一下...

https://github.com/rootsongjc/kubernetes-handbook/pulls

详细如下:

https://github.com/rootsongjc/kubernetes-handbook/blob/master/practice/traefik-ingress-installation.md  中 2处文件名更改..

第1处:
```
创建名为traefik-ingress的ingress，文件名traefik.yaml
```
更新为 
```
创建名为traefik-ingress的ingress，文件名ingress.yaml
```
第2处:
```
修改该文件后可以使用kubectl replace -f traefik.yaml来更新。
```
更新为
```
修改该文件后可以使用kubectl replace -f ingress.yaml来更新。
```

**Comment by rootsongjc** [comment]
PR merged.
