### ISSUE TITLE
helm-install-failure

### ISSUE THREAD

**Issue by tomtsang** [rootsongjc/kubernetes-handbook#119]
## 环境

**版本和配置信息**

- kubernetes版本：v1.8.5
- docker版本：17.11.0-ce
- 网络插件：flanneld-v0.9.0
- etcd: 3.2.12
- heapster: 1.3.0
- 存储类型：无

IP
```
master(node0): 192.168.31.151
node1:192.168.31.152
node2:192.168.31.153
edge-node:192.168.31.154
```
## 操作

**导致该问题的操作或现象**

./get_helm.sh

## 日志

**日志或报错信息**

安装报错

```
[root@udvbct-k8s-edgenode jlch]# ./get_helm.sh
Downloading https://kubernetes-helm.storage.googleapis.com/helm-v2.8.0-linux-amd64.tar.gz
Preparing to install into /usr/local/bin
helm installed into /usr/local/bin/helm
which: no helm in (/sbin:/bin:/usr/sbin:/usr/bin)
helm not found. Is /usr/local/bin on your $PATH?
Failed to install helm
	For support, go to https://github.com/kubernetes/helm.
[root@udvbct-k8s-edgenode jlch]#
```

查看一下 get_helm.sh 文件, 似乎是下面这个位置引起的哟...

```
    164 # testVersion tests the installed client to make sure it is working.
    165 testVersion() {
    166   set +e
    167   echo "$PROJECT_NAME installed into $HELM_INSTALL_DIR/$PROJECT_NAME"
    168   HELM="$(which $PROJECT_NAME)"
    169   if [ "$?" = "1" ]; then
    170     echo "$PROJECT_NAME not found. Is $HELM_INSTALL_DIR on your "'$PATH?'
    171     exit 1
    172   fi
    173   set -e
    174   echo "Run '$PROJECT_NAME init' to configure $PROJECT_NAME."
    175 }
```
---
因为上面显示, helm 安装在了 /usr/local/bin 下 , 是否考虑, root 没有把 这个路径加入到 PATH下 ..
所以, 我考虑用非root用户运行 ./get_helm.sh 

```
[jlch@udvbct-k8s-edgenode ~]$ ./get_helm.sh
Error: cannot connect to Tiller
Helm v2.8.0 is already latest
helm installed into /usr/local/bin/helm
Run 'helm init' to configure helm.
[jlch@udvbct-k8s-edgenode ~]$ which helm
/usr/local/bin/helm
[jlch@udvbct-k8s-edgenode ~]$
```
果然成功了(`Error: cannot connect to Tiller`这一句有影响么?)...

---
1) `Error: cannot connect to Tiller`这一句有影响么?
2) 那 root 安装, 怎么破?
3) helm是一定要安装master节点下么? 还是在 任意一台node节点机下么? 还是内网中任意一台机器?

**Comment by rootsongjc** [comment]
只要在你自己的电脑上执行`./get_helm.sh`即可，而且不需要使用root用户安装。Tiller是作为Kubernetes的中的service安装的。`Error: cannot connect to Tiller`可以先检查你的`Tiller`服务是否正常。

**Comment by tomtsang** [comment]
第1, 我明白了...
第2, 这个如果说是client , 就是说安装在内网中任意一台机器...
第3, tiller作为一个svc, 所以, 必须通过 kubectl 相关联的机器(一般是master)上安装...
@rootsongjc 我这么理解, 正确么?

**Comment by rootsongjc** [comment]
helm其实也是通过调用kubernetes的API来启动chart中的定义的资源的，所以只要在任何一个有admin权限的可以执行kubectl命令操作集群的节点上使用都可以。

**Comment by tomtsang** [comment]
噢.有点理解了...
@rootsongjc 谢谢超哥...
