### ISSUE TITLE
Dashboard 显示问题(不能显示图形)

### ISSUE THREAD

**Issue by aarongo** [rootsongjc/kubernetes-handbook#124]
## 环境

**版本和配置信息**

- kubernetes版本：1.8.6
- docker版本：17.04.0-ce
- 网络插件：Flanneld 0.9.0
- 存储类型：overlay

## 操作

kubectl create -f  .
**导致该问题的操作或现象**
![image](https://user-images.githubusercontent.com/9677127/35425382-6ef059c0-0295-11e8-978b-9f88c084a845.png)

![image](https://user-images.githubusercontent.com/9677127/35425373-56a664f4-0295-11e8-83b4-7d5ee2ec5272.png)

## 日志

**日志或报错信息**

**Comment by rootsongjc** [comment]
heapster部署完成后需要等一段时间，dashboard上才能显示出来图形，大概5到10分钟。
