### ISSUE TITLE
应用日志收集-加镜像

### ISSUE THREAD

**Issue by tomtsang** [rootsongjc/kubernetes-handbook#127]
- 存储类型：无

**说明**

- helm 安装在 master 节点

**IP** 

- master(node0): 192.168.31.151
- node1:192.168.31.152
- node2:192.168.31.153
- edge-node:192.168.31.154

## 操作

**导致该问题的操作或现象**

[应用日志收集](https://jimmysong.io/kubernetes-handbook/practice/app-log-collection.html) 中的
filebeat-test.yaml 文件, 涉及镜像

超哥, 有空时, 加一个 镜像`index.tenxcloud.com/jimmy/analytics-docker-test:Build_8` , 供我们下载测试用吧

```bash
[root@udvbct-k8s-v185-master app-log-collection]# docker pull index.tenxcloud.com/jimmy/analytics-docker-test:Build_8
Error response from daemon: Get https://index.tenxcloud.com/v2/jimmy/analytics-docker-test/manifests/Build_8: unauthorized: authentication required
[root@udvbct-k8s-v185-master app-log-collection]#
```

## 日志

**日志或报错信息**

**Comment by rootsongjc** [comment]
@tomtsang 这个镜像是我们自己测试用的，你可以自己制作一个镜像，只要应用启动后能够持续向某个目录下的文件输出日志即可。
