### ISSUE TITLE
Kubernetes 仪表板通过config和token点击登录无法跳转页面

### ISSUE THREAD

**Issue by weidichen** [rootsongjc/kubernetes-handbook#131]
## 环境
CentOS Linux release 7.3.1611 (Core) 
**版本和配置信息**
dashbord版本 1.8.1和1.8.2
- kubernetes版本：1.8.6 

- docker版本：Docker version 17.12.0-ce, build c97c6d6
- 网络插件：flannel
- 存储类型：nfs

## 操作
Kubernetes 仪表板通过config和token点击登录无法跳转页面，但是观察后台日志，未发现报错，且网页访问时显示状态码为200，但是无法进入登录按钮后的跳转页面，另外用跳过按钮后能正常进入到界面，且能正常操作，当token或者config文件有误时，页面又会提示，验证码错误
**导致该问题的操作或现象**

## 日志

**日志或报错信息**
用config时的登录日志

2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Incoming HTTP/2.0 GET /api/v1/csrftoken/login request from 172.30.62.0:59042: {}
2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Incoming HTTP/2.0 POST /api/v1/login request from 172.30.62.0:59042: {
"kubeConfig": "apiVersion: v1\nclusters:\n- cluster:\n certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVYVR2NWh2Z2FLUVZJS3FmNEszWVFXUTVZWTZVd0RRWUpLb1pJaHZjTkFRR
UwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEU0TURFeU5URXhOREV3TUZvWERUSXpNREV5TkRFeE5ERXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcHMvVVZkOXhDdlJ5VzJrL1hibmUKRmdsdGZQK1pWYlkxMkZDUUFsakdhZDdSVHZvSm80QkZ2eE50TWVoMGlNWTc3bTFPS2xjL3AzL0ozZm9aektKawpqbzlXZkU2STFWMXcwYVBlVTRaNHU1WG1IOXlmUXNlSGpRTU5ST1FYRnVRdWlpeWhxbFJoOW9iQmFRNnlWbFZGCjFWS2VlVy9UK2FteTdLdDdveU9ZMlhIMmM0Z0ZoZy9TdlBlVnhGTHJxaDBKK2VUMEpaUGFqNGhoSEJEbTNYZ0sKV3M3ckVBcWVYNk9IajlBZVBsR0JuS3l5Q054dHRmdjlxTHFQUFJnLzFzVi81Ym52d0MvNm1Ed3poSUtlVy9CTgpndWUzVGJudS85c2FZMDBtUnhGdk40eWxFR3cwc3BCWTlBYWsyRisyTzhxY0FzWnN4WXlBOXBNUXFRa0dUR0o0CitRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVS1VnQUNQVkcrWlpHdXo5alFWbVh3eG9sYlpFd0h3WURWUjBqQkJnd0ZvQVVLVWdBQ1BWRworWlpHdXo5alFWbVh3eG9sYlpFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDOWl1eVdNb09VSzRXZkhqNTdUClZFWGxnckp3M3hTK2dqWDZUcjZQcW9zSHN5bnN0MGNzTmZET1FiSkV2aDFuR1F4cWJpa1J4RmIzUmdKeVRGWlMKYldEa0ZwK055aWdOM1BjQVRWZnRldXdMZGhaNUxuSlE4U3FCTkZWSE1qVk5KWHIxS3lpRmRQdDdUN08xY3J3SwptT3dhbkR4VFBsNUZtWE16UWVZU0dYR1kxRjA0aHZJNWJYUkowUE0rMnp5MlRLVkpKYm56a2IyNWsxM2NNYW5ICnlJQ3k1RGpGZnZQT1pKTXJhZ3dIRWd6R2kwOHltajE4R0d4SDFYQmp1Vm5HZGVYUzZiNGZhcVBPUHNPM0hTbUMKUWtjdmhPY1NKdlgweGplYnJKUVU0bHJKdUJ0bHJ0cmtxWnFkRHFzOVBhRmNVa1dzMVZmdEp2SFBjT3JnejFJZAp2NEU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K\n server: https://172.16.10.204:6443\n name: kubernetes\ncontexts:\n- context:\n cluster: kubernetes\n user: kubelet-bootstrap\n name: default\ncurrent-context: default\nkind: Config\npreferences: {}\nusers:\n- name: kubelet-bootstrap\n user:\n as-user-extra: {}\n token: c2a73a4eb2eaa5e422c4ee406c21fb59\n", "password": "",
"token": "",
"username": ""
}
2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 172.30.62.0:59042: {}
2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Outcoming response to 172.30.62.0:59042 with 200 status code

用token时的登录日志
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Incoming HTTP/2.0 GET /api/v1/csrftoken/login request from 172.30.62.0:59042: {}
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Incoming HTTP/2.0 POST /api/v1/login request from 172.30.62.0:59042: {
"kubeConfig": "",
"password": "",
"token": "c2a73a4eb2eaa5e422c4ee406c21fb59",
"username": ""
}
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 172.30.62.0:59042: {}
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Outcoming response to 172.30.62.0:59042 with 200 status code

点击跳过后的日志，点跳过能正常进入ui界面

2018/02/06 08:50:17 [2018-02-06T08:50:17Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 172.30.62.0:59042: {}
2018/02/06 08:50:17 [2018-02-06T08:50:17Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:17 [2018-02-06T08:50:17Z] Incoming HTTP/2.0 GET /api/v1/overview?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp request from 172.30.62.0:59042: {}
2018/02/06 08:50:17 Getting config category
2018/02/06 08:50:17 Getting discovery and load balancing category
2018/02/06 08:50:17 Getting lists of all workloads
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 Getting pod metrics
2018/02/06 08:50:17 [2018-02-06T08:50:17Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Incoming HTTP/2.0 GET /api/v1/systembanner request from 172.30.62.0:59042: {}
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 172.30.62.0:59042: {}
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Incoming HTTP/2.0 GET /api/v1/rbac/status request from 172.30.62.0:59042: {}
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 172.30.62.0:59042: {}
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Incoming HTTP/2.0 GET /api/v1/overview/default?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp request from 172.30.62.0:59042: {}
2018/02/06 08:50:18 Getting config category
2018/02/06 08:50:18 Getting discovery and load balancing category
2018/02/06 08:50:18 Getting lists of all workloads
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 Getting pod metrics
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Outcoming response to 172.30.62.0:59042 with 200 status code

**Comment by rootsongjc** [comment]
请再附上dashboard的日志以便分析，否则光从描述中来看并不知道是什么问题导致的。

**Comment by weidichen** [comment]
用config时的登录日志

2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Incoming HTTP/2.0 GET /api/v1/csrftoken/login request from 172.30.62.0:59042: {}
2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Incoming HTTP/2.0 POST /api/v1/login request from 172.30.62.0:59042: {
  "kubeConfig": "apiVersion: v1\nclusters:\n- cluster:\n    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVYVR2NWh2Z2FLUVZJS3FmNEszWVFXUTVZWTZVd0RRWUpLb1pJaHZjTkFRR
UwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEU0TURFeU5URXhOREV3TUZvWERUSXpNREV5TkRFeE5ERXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcHMvVVZkOXhDdlJ5VzJrL1hibmUKRmdsdGZQK1pWYlkxMkZDUUFsakdhZDdSVHZvSm80QkZ2eE50TWVoMGlNWTc3bTFPS2xjL3AzL0ozZm9aektKawpqbzlXZkU2STFWMXcwYVBlVTRaNHU1WG1IOXlmUXNlSGpRTU5ST1FYRnVRdWlpeWhxbFJoOW9iQmFRNnlWbFZGCjFWS2VlVy9UK2FteTdLdDdveU9ZMlhIMmM0Z0ZoZy9TdlBlVnhGTHJxaDBKK2VUMEpaUGFqNGhoSEJEbTNYZ0sKV3M3ckVBcWVYNk9IajlBZVBsR0JuS3l5Q054dHRmdjlxTHFQUFJnLzFzVi81Ym52d0MvNm1Ed3poSUtlVy9CTgpndWUzVGJudS85c2FZMDBtUnhGdk40eWxFR3cwc3BCWTlBYWsyRisyTzhxY0FzWnN4WXlBOXBNUXFRa0dUR0o0CitRSURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVS1VnQUNQVkcrWlpHdXo5alFWbVh3eG9sYlpFd0h3WURWUjBqQkJnd0ZvQVVLVWdBQ1BWRworWlpHdXo5alFWbVh3eG9sYlpFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDOWl1eVdNb09VSzRXZkhqNTdUClZFWGxnckp3M3hTK2dqWDZUcjZQcW9zSHN5bnN0MGNzTmZET1FiSkV2aDFuR1F4cWJpa1J4RmIzUmdKeVRGWlMKYldEa0ZwK055aWdOM1BjQVRWZnRldXdMZGhaNUxuSlE4U3FCTkZWSE1qVk5KWHIxS3lpRmRQdDdUN08xY3J3SwptT3dhbkR4VFBsNUZtWE16UWVZU0dYR1kxRjA0aHZJNWJYUkowUE0rMnp5MlRLVkpKYm56a2IyNWsxM2NNYW5ICnlJQ3k1RGpGZnZQT1pKTXJhZ3dIRWd6R2kwOHltajE4R0d4SDFYQmp1Vm5HZGVYUzZiNGZhcVBPUHNPM0hTbUMKUWtjdmhPY1NKdlgweGplYnJKUVU0bHJKdUJ0bHJ0cmtxWnFkRHFzOVBhRmNVa1dzMVZmdEp2SFBjT3JnejFJZAp2NEU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K\n    server: https://172.16.10.204:6443\n  name: kubernetes\ncontexts:\n- context:\n    cluster: kubernetes\n    user: kubelet-bootstrap\n  name: default\ncurrent-context: default\nkind: Config\npreferences: {}\nusers:\n- name: kubelet-bootstrap\n  user:\n    as-user-extra: {}\n    token: c2a73a4eb2eaa5e422c4ee406c21fb59\n",  "password": "",
  "token": "",
  "username": ""
}
2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 172.30.62.0:59042: {}
2018/02/06 08:51:56 [2018-02-06T08:51:56Z] Outcoming response to 172.30.62.0:59042 with 200 status code



用token时的登录日志
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Incoming HTTP/2.0 GET /api/v1/csrftoken/login request from 172.30.62.0:59042: {}
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Incoming HTTP/2.0 POST /api/v1/login request from 172.30.62.0:59042: {
  "kubeConfig": "",
  "password": "",
  "token": "c2a73a4eb2eaa5e422c4ee406c21fb59",
  "username": ""
}
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 172.30.62.0:59042: {}
2018/02/06 08:53:13 [2018-02-06T08:53:13Z] Outcoming response to 172.30.62.0:59042 with 200 status code


点击跳过后的日志，点跳过能正常进入ui界面

2018/02/06 08:50:17 [2018-02-06T08:50:17Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 172.30.62.0:59042: {}
2018/02/06 08:50:17 [2018-02-06T08:50:17Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:17 [2018-02-06T08:50:17Z] Incoming HTTP/2.0 GET /api/v1/overview?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp request from 172.30.62.0:59042: {}
2018/02/06 08:50:17 Getting config category
2018/02/06 08:50:17 Getting discovery and load balancing category
2018/02/06 08:50:17 Getting lists of all workloads
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 No metric client provided. Skipping metrics.
2018/02/06 08:50:17 Getting pod metrics
2018/02/06 08:50:17 [2018-02-06T08:50:17Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Incoming HTTP/2.0 GET /api/v1/systembanner request from 172.30.62.0:59042: {}
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 172.30.62.0:59042: {}
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Incoming HTTP/2.0 GET /api/v1/rbac/status request from 172.30.62.0:59042: {}
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Incoming HTTP/2.0 GET /api/v1/login/status request from 172.30.62.0:59042: {}
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Outcoming response to 172.30.62.0:59042 with 200 status code
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Incoming HTTP/2.0 GET /api/v1/overview/default?filterBy=&itemsPerPage=10&name=&page=1&sortBy=d,creationTimestamp request from 172.30.62.0:59042: {}
2018/02/06 08:50:18 Getting config category
2018/02/06 08:50:18 Getting discovery and load balancing category
2018/02/06 08:50:18 Getting lists of all workloads
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 No metric client provided. Skipping metrics.
2018/02/06 08:50:18 Getting pod metrics
2018/02/06 08:50:18 [2018-02-06T08:50:18Z] Outcoming response to 172.30.62.0:59042 with 200 status code

**Comment by kuviki** [comment]
见 https://github.com/kubernetes/dashboard/issues/2735
