### ISSUE TITLE
etcd-绑定监听端口失败

### ISSUE THREAD

**Issue by YuanLicc** [rootsongjc/kubernetes-handbook#146]
## 环境
阿里云服务器，Centos7 1核2G，已关闭防火墙，已设置安全组为允许任意端口出入(阿里云安全组)
**版本和配置信息**

- kubernetes版本：v1.6.0
- docker版本：还没装
- 网络插件：还没装
- 存储类型：etcd键值

## 操作
安装etcd集群
**导致该问题的操作或现象**
配置etcd监听本机ip及端口，出现了监听失败无法启动，将ip改为127.0.0.1是可以启动etcd的
## 日志

```
Mar 09 21:39:57 iZwz95dly2y6k9zo0fd771Z etcd[12272]: etcd Version: 3.1.5
Mar 09 21:39:57 iZwz95dly2y6k9zo0fd771Z etcd[12272]: Git SHA: 20490ca
Mar 09 21:39:57 iZwz95dly2y6k9zo0fd771Z etcd[12272]: Go Version: go1.7.5
Mar 09 21:39:57 iZwz95dly2y6k9zo0fd771Z etcd[12272]: Go OS/Arch: linux/amd64
Mar 09 21:39:57 iZwz95dly2y6k9zo0fd771Z etcd[12272]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Mar 09 21:39:57 iZwz95dly2y6k9zo0fd771Z etcd[12272]: peerTLS: cert = /etc/kubernetes/ssl/kubernetes.pem, key = /etc/kubernetes/ssl/kubernetes-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/ca.pem, client-cert-auth = false
Mar 09 21:39:57 iZwz95dly2y6k9zo0fd771Z etcd[12272]: **listen tcp 120.77.171.82:2380: bind: cannot assign requested address**
Mar 09 21:39:57 iZwz95dly2y6k9zo0fd771Z systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Mar 09 21:39:57 iZwz95dly2y6k9zo0fd771Z systemd[1]: Failed to start Etcd Server.
```
**日志或报错信息**

**Comment by rootsongjc** [comment]
@YuanLicc 能附上你的etcd配置吗？

**Comment by YuanLicc** [comment]
@rootsongjc 哥，这几天我请教了下群里的老哥们，已经解决了。
说一下我的理解：
首先我搭建的环境是阿里云服务器，网络为vpc
在搭建etcd集群时使用公网Ip作为监听url的一部分是错误的，应该使用内网ip，且保证服务器在同一区域下，也就是同一网络环境下，所以我觉得在公有云上搭建时都应该先了解下网络环境。若使用经典网络，公网ip应该是可行的，我没有试过，也对这方面的知识不是很了解。
新生的问题，是否k8s的搭建也有同样的网络环境限制呢？

**Comment by rootsongjc** [comment]
@YuanLicc 公有云上网络环境比较复杂，在部署kubernetes中的组件前应该先了解下所使用的云场上提供的网络环境。如果使用的是VPC，那么直接使用内网的IP。容器间的网络需要使用网络插件实现，这个需要对网络插件所支持的网络也要有一定了解，比如flannel的`host-gw`模式只支持二层网络，而vxlan是可以跨VPC使用的。

**Comment by rootsongjc** [comment]
@YuanLicc I think so.

**Comment by YuanLicc** [comment]
@rootsongjc Thanks, old brother，I will try

**Comment by yummykang** [comment]
@YuanLicc 可以说说你是怎么解决的吗

**Comment by YuanLicc** [comment]
换了同网络下的机子并使用内网ip进行集群,如果是阿里服务器的话，选择同一地区下的服务器就行了，比如说华南，同一地区下的机子属于同一网络下的。当然也可以像大佬说的解决跨vpc的问题，然后使用公网ip。这种我没有试过。建议还是内网下进行搭建。

**Comment by YuanLicc** [comment]
@yummykang 换了同网络下的机子并使用内网ip进行集群,如果是阿里服务器的话，选择同一地区下的服务器就行了，比如说华南，同一地区下的机子属于同一网络下的。当然也可以像大佬说的解决跨vpc的问题，然后使用公网ip。这种我没有试过。建议还是内网下进行搭建。

**Comment by yummykang** [comment]
@YuanLicc 好的，谢谢

**Comment by klkyy** [comment]
@YuanLicc 搭建etcd集群时使用公网Ip作为监听url的一部分是错误?  这是为什么？我也遇到同样的错误了，求教

**Comment by feixiaohuijava** [comment]
我也是使用公网ip，然后创建kubernets.pem 和kubernets-key.pem两个文件。然后报了同样的错误，使用局域网ip就可以了~

**Comment by jaffe-fly** [comment]
公网ip就没有办法了吗
