### ISSUE TITLE
8.6章节-问题记录中的 “6.PVC中对Storage的容量设置不生效“  描述是否有错误

### ISSUE THREAD

**Issue by whmzsu** [rootsongjc/kubernetes-handbook#153]
“当时给glusterfs-nginx的PVC设置了8G的存储限额，nginx-dm这个Deployment使用了该PVC“
但是测试的时候并没有在PV里面测试，可以看到PV的挂载位置是/usr/share/nginx/html, 限额测试的位置是~/，即/root位置
由于devicemapper 后端驱动在docker里默认的大小是10GB，通过挂载信息可以看到10GB，已经使用228M，空余9.8GB，因此你的dd测试可以放下9GB的空间是正常的，并不能说明限额配置没有起作用。建议在PV的挂载路径下/usr/share/nginx/html,重新测试一下。
whmzsu@gmail.com  mingo

**Comment by rootsongjc** [comment]
@whmzsu 不知你有没有测试结果可以给大家提供参考？

**Comment by whmzsu** [comment]
我使用heketi的方法，即外部storage provisioner 的方法是可以的，pvc 2G，生成pv2g，容量dd写入最大2g，这里图片不好贴。文档里面的看起来是使用内部的provisioner， 这种方法没有试过。
使用heketi的参考文档在这里  https://github.com/heketi/heketi/blob/master/docs/admin/install-kubernetes.md，   周末有空可以翻译一下。

**Comment by whmzsu** [comment]
https://pan.baidu.com/s/1x0vAaH30LoCz8jQqk5vyKA 
翻译好了，没怎么排版

**Comment by rootsongjc** [comment]
@whmzsu 你可以直接提交PR，我merge一下一下就行了。

**Comment by whmzsu** [comment]
这个真的要周末了，还没写过gitbook，周末学习一下

**Comment by whmzsu** [comment]
已提交PR，麻烦帮忙审核
