### ISSUE TITLE
curl不通service ip

### ISSUE THREAD

**Issue by BigbigY** [rootsongjc/kubernetes-handbook#162]
## 环境

**版本和配置信息**

- kubernetes版本：1.9.2
- docker版本：17.12.0-ce
- 网络插件：
- 存储类型：

## 操作
安装文档装完node节点，准备测试，安装文档操作安装nginx

**导致该问题的操作或现象**
curl 10.254.207.75 不通nginx

## 日志

**日志或报错信息**

查看kubete以下错误
```
E0403 14:19:57.813509   26754 fs.go:418] Stat fs failed. Error: no such file or directory
```

**Comment by rootsongjc** [comment]
curl 本身就是不通的，需要加上service的端口才可以。

**Comment by lyc20140320** [comment]
我也遇到这个问题，加上端口也不通 curl 10.254.99.140:80,用各节点的ip访问时可以的

[root@k8s-master kubernetes]# kubectl get service
NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
example-service   NodePort    10.254.99.140   <none>        80:30854/TCP   4m
kubernetes        ClusterIP   10.254.0.1      <none>        443/TCP        1d
[root@k8s-master kubernetes]# curl 10.254.99.140：30854
curl: (6) Could not resolve host: 10.254.99.140:30854; Name or service not known
[root@k8s-master kubernetes]# curl 10.254.99.140:30854
^C
[root@k8s-master kubernetes]# curl 10.254.99.140:80
^C
[root@k8s-master kubernetes]# kubectl describe svc example-service
Name:                     example-service
Namespace:                default
Labels:                   run=load-balancer-example
Annotations:              <none>
Selector:                 run=load-balancer-example
Type:                     NodePort
IP:                       10.254.99.140
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  30854/TCP
Endpoints:                172.17.0.2:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

**Comment by BigbigY** [comment]
```
[root@hz-k8s-cluster-n01 example]# kubectl run nginx --replicas=2 --labels="run=load-balancer-example" --image=nginx:v1.9.9 --port=80
deployment "nginx" created
[root@hz-k8s-cluster-n01 example]# kubectl expose deployment nginx --type=NodePort --name=example-service
service "example-service" exposed
[root@hz-k8s-cluster-n01 example]# kubectl describe svc example-service
Name:                     example-service
Namespace:                default
Labels:                   run=load-balancer-example
Annotations:              <none>
Selector:                 run=load-balancer-example
Type:                     NodePort
IP:                       10.254.49.120
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  31684/TCP
Endpoints:                192.168.0.3:80,192.168.0.3:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
[root@hz-k8s-cluster-n01 example]# curl "10.254.49.120:80"
```

**Comment by BigbigY** [comment]
明白了，文章中是master也作为node来装的，也装来kube-proxy才能在master curl到，而我master没有kube-proxy，所以就curl不到，我在node节点就可以curl到了，是这样吧

**Comment by rootsongjc** [comment]
是的，就就是这样的 @BigbigY

**Comment by BigbigY** [comment]
感谢 @rootsongjc 
我还有一个问题，我再提一个issue吧

**Comment by lyc20140320** [comment]
@rootsongjc  我的docker不能被flannel托管是怎么回事呢

**Comment by rootsongjc** [comment]
@lyc20140320 不明白你的问题，你可以再提一个issue。
