### ISSUE TITLE
ConfigMap强制滚动更新

### ISSUE THREAD

**Issue by tnextday** [rootsongjc/kubernetes-handbook#168]
3.9.2.1 `ConfigMap的热更新` 中说：

> ConfigMap，也可以在更新了 ConfigMap 后，先将副本数设置为 0，然后再扩容。

可以通过在 `.spec.template.metadata.annotations` 中增加一个额外项来实现，
例如 `checksum/config `, 每次更新只要改下这个值就可以了

参考 [Automatically Roll Deployments When ConfigMaps or Secrets change](https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change)

**Comment by rootsongjc** [comment]
@tnextday 感谢你的建议，如果你愿意的话可以直接提交一个PR对ConfigMap的热更新一节进行补充。
