### ISSUE TITLE
帅哥，按照你的文档生成admin.pem，配置完kubectl配置文件，使用kubectl命令报错

### ISSUE THREAD

**Issue by Jerry1Q84** [rootsongjc/kubernetes-handbook#17]
[root@sz-pg-oam-docker-test-001 ~]# kubectl get pods
error: You must be logged in to the server (the server has asked for the client to provide credentials)

May 26 14:26:32 localhost kube-apiserver: E0526 14:26:32.855345    7045 authentication.go:58] Unable to authenticate the request due to an error: x509: certificate specifies an incompatible key usage

**Comment by rootsongjc** [comment]
该问题是否已经解决？

**Comment by Jerry1Q84** [comment]
没有，卡在这了。

**Comment by rootsongjc** [comment]
请注意修改你配置中的主机名为你自己的真实主机名，不要完全照搬我的配置。
