### ISSUE TITLE
使用Jenkins进行持续集成与发布除了第一次之外，后续的都不生效

### ISSUE THREAD

**Issue by zhuima** [rootsongjc/kubernetes-handbook#171]
## 环境

**版本和配置信息**

- kubernetes版本：1.8.3
- docker版本：17.03.2-ce
- 网络插件：clico
- 存储类型：本地

## 操作

**导致该问题的操作或现象**

https://jimmysong.io/kubernetes-handbook/practice/jenkins-ci-cd.html
文档中描述的第5步操作，如果作为第一步发布确实是没问题的，但是作为第二步发布的话，就不生效了

操作步骤：
1、python + jinja2生成可用的p1项目的yaml文件
      (包含Deployment,Service和Ingress)两个文件(每次变动的只是镜像不一致而已)
      
2、rsync到k8s的master节点上p1项目对应的目录下去
3、在jenkins机器上对k8s的master节点上的p1项目目录下执行kubectl apply *.yaml
4、后续(第二次以后)的发布就不生效了（也就是说新的image并没有running起来）

## 日志

**日志或报错信息**

**Comment by rootsongjc** [comment]
@zhuima 你可以先确认下第二次运行替换 image 的时候 `kubectl apply *.yaml`命令有没有实际执行。

**Comment by zhuima** [comment]
查看日志发现了其中的一个节点报错如下，就是这台机器上出现了问题

`nsenter: failed to unshare namespaces: Cannot allocate memory
container_linux.go:247: starting container process caused "process_linux.go:245: running exec setns process for init caused \"exit status 29\""
oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:245: running exec setns process for init caused \"exit status 29\""`

然后跟踪发现了这个文档

> https://blog.csdn.net/wqhlmark64/article/details/79143975


问题暂时没解

**Comment by whmzsu** [comment]
加一个节点试试，或者把部署容器的资源request参数去掉，你给的参考链接里说了大致原因
1 资源不够了
2 资源够，但是内存分配太碎了，无法完整提供整块的内存

**Comment by NickSu86** [comment]
我剛剛碰見這個問題，結果發現機器上面跑了 spark 吃了很多 cache 內存，把spark搬走後就好了
