### ISSUE TITLE
cephfs那里的文档结构是否可以调整一下

### ISSUE THREAD

**Issue by whmzsu** [rootsongjc/kubernetes-handbook#176]
当前目录：最佳实践->存储管理->cephfs->使用Ceph做持久化存储创建MySQL集群

cephfs  应该改为ceph，因为ceph是一个整体解决方案，包括cephfs，cephrbd，ceph对象存储三个主要接口，当前kubernetes支持cephfs和cephrbd作为后端存储。

并且《使用Ceph做持久化存储创建MySQL集群》这批文档看起来是以cephrbd作为后端存储，与上级标题cephfs容易引起混淆。

因此建议改成：最佳实践->存储管理->ceph->使用Ceph-rdb做持久化存储创建MySQL集群。修改同时修改cephfs章节的描述为ceph的介绍
这样后续可以在子目录下继续添加cephfs相关的实践文档。

**Comment by rootsongjc** [comment]
Good idea! 欢迎提交PR修改下文档目录。
