### ISSUE TITLE
kubernetes-csr.json 如何hosts 有没有办法写通配符，不然扩容不好实现

### ISSUE THREAD

**Issue by amwuqd** [rootsongjc/kubernetes-handbook#186]
## 环境

**版本和配置信息**

- kubernetes版本：V1.9.1
- docker版本： 1.13.1
- 网络插件：flannel
- 存储类型：

## 操作
 
**kubernetes-csr.json 如何hosts 有没有办法写通配符，不然扩容不好实现，例如10.0.10.0/24**

## 日志

**日志或报错信息**

**Comment by rootsongjc** [comment]
证书只要生成一次就好，不需要把所有的IP都增加进去，后面的增加的节点可以复用证书。

**Comment by amwuqd** [comment]
但后续增加节点的时候报错误
 x509: cannot validate certificate for 192.168.50.135 because it doesn't contain any IP SANs

**Comment by 573009114** [comment]
这个问题同求答案。。。

**Comment by DaleSin** [comment]
同求解答
