### ISSUE TITLE
kube-proxy start error .

### ISSUE THREAD

**Issue by KevinDavidMitnick** [rootsongjc/kubernetes-handbook#19]
docker version 1.12
os: centos7.3.1611
 
897 conntrack.go:42] conntrack returned error: error looking for path of conntrack: exec: "conntrack": executable file not found in $PATH
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by rootsongjc** [comment]
该问题已经在`appendix/issues.md`文件中记录。[点此查看](https://github.com/rootsongjc/kubernetes-handbook/blob/master/appendix/issues.md#4kube-proxy报错kube-proxy2241-e0502-155513889842----2241-conntrackgo42-conntrack-returned-error-error-looking-for-path-of-conntrack-exec-conntrack-executable-file-not-found-in-path)
**解决方法**
CentOS中安装conntrack-tools包后重启kubernetes集群即可。
