### ISSUE TITLE
关于GitHub 存在的两个kubernetes-handbook项目的疑问

### ISSUE THREAD

**Issue by ToQuery** [rootsongjc/kubernetes-handbook#192]
## 目前GitHub 存在两个 kubernetes-handbook

- https://github.com/rootsongjc/kubernetes-handbook
- https://github.com/feiskyer/kubernetes-handbook

这两个项目有什么联系，还是完全独立的两个项目？

**Comment by rootsongjc** [comment]
@ToQuery 这两个项目是完全独立的，不过是我先公开的，但是 @feiskyer 又跟我不约而同的用了同一个项目名字，在我公开之前 @feiskyer 也在用该项目名在写，只是没发布而已。后来我们合并过一次，大概是2017年5月吧，然后又各自分开写了。

**Comment by ToQuery** [comment]
好的，了解了
