### ISSUE TITLE
kubernetes hpa 无法获取值

### ISSUE THREAD

**Issue by augafox** [rootsongjc/kubernetes-handbook#196]
## 环境

**版本和配置信息**

- kubernetes版本： 1.9.1
- docker版本：17.05.0-ce
- 网络插件： flanneld
- 存储类型：

## 操作

**导致该问题的操作或现象**
heapster 安装后。dashboard 可以获取监控信息。 heapster接口正常 但是HPA无法获取数据
## 日志

**日志或报错信息**

```bash
  Warning  FailedGetResourceMetric       3m (x13 over 9m)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
  Warning  FailedComputeMetricsReplicas  3m (x13 over 9m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
```

**Comment by augafox** [comment]
hepster 安装我用的如下 yaml文件。并将里面的镜像改为了 V1.5.0  https://raw.githubusercontent.com/kubernetes/kops/master/addons/monitoring-standalone/v1.7.0.yaml

**Comment by iiitux** [comment]
这问题之前在微信里讨论过，我也1.9版本碰到这个问题，我是在controller manager启动参数--horizontal-pod-autoscaler-use-rest-clients=false解决的，参考 issue https://github.com/kubernetes/kubernetes/issues/57673。

也有兄弟说现在部署metric server也可以解决，我没试过。

**Comment by YuPengZTE** [comment]
用最新的metric server也遇到无法获取值得情况
ubuntu:~/metrics-server/deploy/1.8+$ kubectl get hpa
NAME               REFERENCE                        TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
hpa-test-app-hpa   Deployment/hpa-test-app-deploy   <unknown>/70%   1         10        0          22h

但是
ubuntu:~/metrics-server/deploy/1.8+$ kubectl top nodes
NAME       CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%
master01   224m         5%        2315Mi          23%
minion01   197m         4%        1966Mi          20%
minion02   136m         3%        1600Mi          16%
minion03   81m          2%        949Mi           9%

节点信息：
ubuntu:~/metrics-server/deploy/1.8+$ kubectl get node
NAME       STATUS    ROLES     AGE       VERSION
master01   Ready     master    43d       v1.12.2
minion01   Ready     <none>    43d       v1.12.2
minion02   Ready     <none>    43d       v1.12.2
minion03   Ready     <none>    43d       v1.12.2

目前还不知道怎么获取到值。
@iiitux 有啥建议不？谢谢！
