### ISSUE TITLE
安装ELK后无法访问打开

### ISSUE THREAD

**Issue by ghost** [rootsongjc/kubernetes-handbook#199]
## 环境

**版本和配置信息**

- kubernetes版本：1.9
- docker版本：
- 网络插件：flanneld
- 存储类型：

## 操作
使用https://master_ip:6443/api/v1/namespaces/kube-system/services/kibana-logging/proxy访问报如下错误

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "services \"kibana-logging\" is forbidden: User \"system:anonymous\" cannot get services/proxy in the namespace \"kube-system\"",
  "reason": "Forbidden",
  "details": {
    "name": "kibana-logging",
    "kind": "services"
  },
  "code": 403
}
```

如果使用代理kubectl proxy --address='0.0.0.0' --port=8086 --accept-hosts='^*$'
http://master_ip:8086/api/v1/proxy/namespaces/kube-system/services/kibana-logging/报如下错误
Error: 'dial tcp 172.30.24.3:5601: getsockopt: no route to host'
Trying to reach: 'http://172.30.24.3:5601/'

这是什么原因，如何解决

## 日志
日志都是正常的

**Comment by rootsongjc** [comment]
@lyc20140320 你查看下ELK容器的日志看看。
