### ISSUE TITLE
pod中多个容器的启动顺序

### ISSUE THREAD

**Issue by jamesalice123** [rootsongjc/kubernetes-handbook#200]
## 环境
centos7.4
**版本和配置信息**

- kubernetes版本：1.7
- docker版本：1.13.1
- 网络插件：calico
- 存储类型：

## 操作
在一个pod中运行多个容器（jar包做成的镜像来运行容器），容器之间启动需要时间间隔，jimmy说这是probe场景，但我还是没明白，在资料中看到的关于probe是一个健康检测来着
**导致该问题的操作或现象**

## 日志

**日志或报错信息**

**Comment by rootsongjc** [comment]
duplicated with #197
