### ISSUE TITLE
k8s集群添加worker节点kubelet启动不会生成/etc/kubernetes/ssl/kubelet-client.crt

### ISSUE THREAD

**Issue by kissingtiger** [rootsongjc/kubernetes-handbook#205]
## 环境
centos7.3
k8s集群worker节点IP： 10.0.3.177
**版本和配置信息**
- kubernetes版本：1.10.1
- docker版本： 17.05.0-ce
- 网络插件：flannel 0.10
- 存储类型：

## 操作
机器worker节点启动kubelet报错
**导致该问题的操作或现象**
我启动kubelet： systemctl start kubelet
```
cat /etc/systemd/system/kubelet.service 
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
WorkingDirectory=/var/lib/kubelet
ExecStart=/root/local/bin/kubelet \
  --address=10.0.3.177 \
  --hostname-override=10.0.3.177 \
  --pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest \
  --bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig \
  --kubeconfig=/etc/kubernetes/kubelet.kubeconfig \
  --cert-dir=/etc/kubernetes/ssl \
  --cluster-dns=10.254.0.2 \
  --cluster-domain=cluster.local. \
  --hairpin-mode promiscuous-bridge \
  --allow-privileged=true \
  --serialize-image-pulls=false \
  --logtostderr=true \
  --v=0
#ExecStartPost=/sbin/iptables -A INPUT -s 10.0.0.0/8 -p tcp --dport 4194 -j ACCEPT
#ExecStartPost=/sbin/iptables -A INPUT -s 172.16.0.0/12 -p tcp --dport 4194 -j ACCEPT
#ExecStartPost=/sbin/iptables -A INPUT -s 192.168.0.0/16 -p tcp --dport 4194 -j ACCEPT
#ExecStartPost=/sbin/iptables -A INPUT -p tcp --dport 4194 -j DROP
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```
## 日志

**日志或报错信息**

```
systemctl status kubelet -l
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-04-27 10:32:18 CST; 1s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 10342 (kubelet)
   Memory: 13.0M
   CGroup: /system.slice/kubelet.service
           └─10342 /root/local/bin/kubelet --address=10.0.3.177 --hostname-override=10.0.3.177 --pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest --bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --cert-dir=/etc/kubernetes/ssl --cluster-dns=10.254.0.2 --cluster-domain=cluster.local. --hairpin-mode promiscuous-bridge --allow-privileged=true --serialize-image-pulls=false --logtostderr=true --v=0

Apr 27 10:32:18 k8s-n4 kubelet[10342]: Flag --serialize-image-pulls has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 27 10:32:18 k8s-n4 kubelet[10342]: I0427 10:32:18.107360   10342 feature_gate.go:226] feature gates: &{{} map[]}
Apr 27 10:32:18 k8s-n4 kubelet[10342]: W0427 10:32:18.113435   10342 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Apr 27 10:32:18 k8s-n4 kubelet[10342]: W0427 10:32:18.116998   10342 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
Apr 27 10:32:18 k8s-n4 kubelet[10342]: I0427 10:32:18.117031   10342 server.go:376] Version: v1.10.1
Apr 27 10:32:18 k8s-n4 kubelet[10342]: I0427 10:32:18.117102   10342 feature_gate.go:226] feature gates: &{{} map[]}
Apr 27 10:32:18 k8s-n4 kubelet[10342]: I0427 10:32:18.117244   10342 plugins.go:89] No cloud provider specified.
Apr 27 10:32:18 k8s-n4 kubelet[10342]: E0427 10:32:18.119109   10342 bootstrap.go:179] Unable to read existing bootstrap client config: invalid configuration: unable to read client-cert /etc/kubernetes/ssl/kubelet-client.crt for default-auth due to open /etc/kubernetes/ssl/kubelet-client.crt: no such file or directory
```

**Comment by rootsongjc** [comment]
我想可能是在你创建 kubernetes 证书和私钥的时候出了问题。

**Comment by kissingtiger** [comment]
具体是哪个证书能猜测一下吗？

**Comment by rootsongjc** [comment]
我不知道你创建证书的具体步骤，如果正常的话应该会生成`kubelet-client.crt`文件才对。

**Comment by kissingtiger** [comment]
找到问题，我只要启动kubelet的时候 执行kubectl certificate approve 去接受 一下就好了，但是我不明白的是为啥我不接受，他会一直创建csr 
node-csr-fs874RfAO4p3FgQmv06Mgz1vUqJZkWihQHPGQd2_eNQ   40m       kubelet-bootstrap   Pending
node-csr-g0edP3orfJhHXh8ku4iCvfqvmeg9dNjjgSOChTxxti4   6m        kubelet-bootstrap   Pending
node-csr-gE4d6999354piR9QG5xOvpufeuiuh5wZvtSy8I-ThTA   45m       kubelet-bootstrap   Pending
node-csr-hEsQKgeNHqS51S8nHUaGR4IQe56mIW3jfM7miQanDOA   37m       kubelet-bootstrap   Pending
node-csr-iB6aO-2Fdxfx2hmxoGqHZxRR3DrigXrdrYNH4rNshfY   4m        kubelet-bootstrap   Pending
node-csr-iKzpQmWuvSUWyLXJzBS_VNcy62DJuIDTYhwjCUb8Lm0   1h        kubelet-bootstrap   Pending
node-csr-j1e1eilsYsGH4OajIRAc1DkxjN6gzVJYsENB-zqtm5A   1h        kubelet-bootstrap   Pending
node-csr-jeO_byNIGB2uAzFENsDDn8H5Uwj1ORtwbosdAror1s4   17m       kubelet-bootstrap   Pending
node-csr-krCMzG6sRLlTSbXkR5Q6WYL6bGYKiEfyFTYElPv4aRs   56m       kubelet-bootstrap   Pending
node-csr-l7OYX7F_LbP4qCBgUqIDEFekLHwlllLdajktAL0MkSs   44m       kubelet-bootstrap   Pending
node-csr-mRVk2Ov2vg8atF_rvz5HzfSe9BPcuvKVfKKLXiK8v0A   51m       kubelet-bootstrap   Pending
node-csr-njBCYqvC0wj-gVQYSipakJK21OC_NPG4AXOJgr00YeA   42m       kubelet-bootstrap   Pending
node-csr-oIS3dGdPh1JsyK14Fi-qHTRq3eov5Iv3VVBIlSK4G6c   41m       kubelet-bootstrap   Pending
node-csr-oXYgTJldXm8da4mrD10nvvsH9qV8ahZqWmbW8XQ1AT0   1h        kubelet-bootstrap   Pending
node-csr-q86wOMi5MfLlH6CL1od3dDg2Cu6mjaCzA03m24yep5Q   16m       kubelet-bootstrap   Pending
node-csr-qdzbh8S9UDiVRQdmZ8ntPCPld3Uw1wA1jWkfNJ5ujFY   26m       kubelet-bootstrap   Pending
node-csr-qtW1oUU564FknCvVJ9ZIwjKG3IchVYLaonH9Lx8JlyQ   1h        kubelet-bootstrap   Pending
node-csr-rKUJxfDYpdMRfBsDxA_w8wEbjzQ8jWtg7l8-5_JrLrM   52m       kubelet-bootstrap   Pending
node-csr-sKqVw3P6zzbgUhaD96zD4mbNKQKsRL4wRAq0XIc_LWU   1h        kubelet-bootstrap   Pending
node-csr-sxmQIXLs-Jv7rwzzXX4lvFVKjOlits5b_6UUDtX6FnI   30m       kubelet-bootstrap   Pending
node-csr-uxEnD0d9BcEMMa-mzwIRNWjKWQ0Rc0CpgQTg7LRB0tI   18m       kubelet-bootstrap   Pending
node-csr-wF3E5PzD7rFWEb0QsrZ8jplWPIkV1tspaVXk6_GGXXM   5m        kubelet-bootstrap   Pending
node-csr-wcTKnbBxwQAANb6cPiWiJ2yDx42ajaxN0dvI1hT3n1c   1h        kubelet-bootstrap   Pending
node-csr-xB8wIbgycgMjEGTbO-RK6rAwaxx9ywhV_ZWA5j8y598   1h        kubelet-bootstrap   Pending
node-csr-xXSZOygY_kuTdf6Vt3rLro5IngBm99eUTv_Uw2mvxA8   7m        kubelet-bootstrap   Pending
node-csr-yPv31H8dlzZFbrOP6-eOAxE4YJawhfLuxalKYzM1I7w   39m       kubelet-bootstrap   Pending

**Comment by kissingtiger** [comment]
kubelet启动日志
Apr 26 19:41:26 k8s-n4 systemd: Started Kubernetes Kubelet.
Apr 26 19:41:26 k8s-n4 systemd: Starting Kubernetes Kubelet...
Apr 26 19:41:26 k8s-n4 kubelet: Flag --address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:41:26 k8s-n4 kubelet: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:41:26 k8s-n4 kubelet: Flag --allow-privileged has been deprecated, will be removed in a future version
Apr 26 19:41:26 k8s-n4 kubelet: I0426 19:41:26.904891    8416 feature_gate.go:226] feature gates: &{{} map[]}
Apr 26 19:41:26 k8s-n4 systemd: Started Kubernetes systemd probe.
Apr 26 19:41:26 k8s-n4 systemd: Starting Kubernetes systemd probe.
Apr 26 19:41:26 k8s-n4 kubelet: W0426 19:41:26.911146    8416 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Apr 26 19:41:26 k8s-n4 kubelet: W0426 19:41:26.914946    8416 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
Apr 26 19:41:26 k8s-n4 kubelet: I0426 19:41:26.915341    8416 plugins.go:89] No cloud provider specified.
Apr 26 19:42:26 k8s-n4 kubelet: F0426 19:42:26.995576    8416 server.go:233] failed to run Kubelet: timed out waiting for the condition
Apr 26 19:42:27 k8s-n4 systemd: kubelet.service: main process exited, code=exited, status=255/n/a
Apr 26 19:42:27 k8s-n4 systemd: Unit kubelet.service entered failed state.
Apr 26 19:42:27 k8s-n4 systemd: kubelet.service failed.
Apr 26 19:42:32 k8s-n4 systemd: kubelet.service holdoff time over, scheduling restart.
Apr 26 19:42:32 k8s-n4 systemd: Cannot add dependency job for unit firewalld.service, ignoring: Unit is masked.
Apr 26 19:42:32 k8s-n4 systemd: Started Kubernetes Kubelet.
Apr 26 19:42:32 k8s-n4 systemd: Starting Kubernetes Kubelet...
Apr 26 19:42:32 k8s-n4 kubelet: Flag --address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:42:32 k8s-n4 kubelet: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:42:32 k8s-n4 kubelet: Flag --allow-privileged has been deprecated, will be removed in a future version
Apr 26 19:42:32 k8s-n4 kubelet: I0426 19:42:32.126710    8455 feature_gate.go:226] feature gates: &{{} map[]}
Apr 26 19:42:32 k8s-n4 systemd: Started Kubernetes systemd probe.
Apr 26 19:42:32 k8s-n4 systemd: Starting Kubernetes systemd probe.
Apr 26 19:42:32 k8s-n4 kubelet: W0426 19:42:32.132624    8455 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Apr 26 19:42:32 k8s-n4 kubelet: W0426 19:42:32.136843    8455 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
Apr 26 19:42:32 k8s-n4 kubelet: I0426 19:42:32.137111    8455 plugins.go:89] No cloud provider specified.
Apr 26 19:43:32 k8s-n4 kubelet: F0426 19:43:32.228840    8455 server.go:233] failed to run Kubelet: timed out waiting for the condition
Apr 26 19:43:32 k8s-n4 systemd: kubelet.service: main process exited, code=exited, status=255/n/a
Apr 26 19:43:32 k8s-n4 systemd: Unit kubelet.service entered failed state.
Apr 26 19:43:32 k8s-n4 systemd: kubelet.service failed.
Apr 26 19:43:37 k8s-n4 systemd: kubelet.service holdoff time over, scheduling restart.
Apr 26 19:43:37 k8s-n4 systemd: Cannot add dependency job for unit firewalld.service, ignoring: Unit is masked.
Apr 26 19:43:37 k8s-n4 systemd: Started Kubernetes Kubelet.
Apr 26 19:43:37 k8s-n4 systemd: Starting Kubernetes Kubelet...
Apr 26 19:43:37 k8s-n4 kubelet: Flag --address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:43:37 k8s-n4 kubelet: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:43:37 k8s-n4 kubelet: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:43:37 k8s-n4 kubelet: Flag --hairpin-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:43:37 k8s-n4 kubelet: Flag --allow-privileged has been deprecated, will be removed in a future version
Apr 26 19:43:37 k8s-n4 kubelet: I0426 19:43:37.383491    8495 feature_gate.go:226] feature gates: &{{} map[]}
Apr 26 19:43:37 k8s-n4 systemd: Started Kubernetes systemd probe.
Apr 26 19:43:37 k8s-n4 systemd: Starting Kubernetes systemd probe.
Apr 26 19:43:37 k8s-n4 kubelet: W0426 19:43:37.388820    8495 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Apr 26 19:43:37 k8s-n4 kubelet: W0426 19:43:37.393559    8495 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
Apr 26 19:43:37 k8s-n4 kubelet: I0426 19:43:37.393648    8495 server.go:376] Version: v1.10.1
Apr 26 19:43:37 k8s-n4 kubelet: I0426 19:43:37.393723    8495 feature_gate.go:226] feature gates: &{{} map[]}
Apr 26 19:43:37 k8s-n4 kubelet: Flag --address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:43:37 k8s-n4 kubelet: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:43:37 k8s-n4 kubelet: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:43:37 k8s-n4 kubelet: Flag --hairpin-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:43:37 k8s-n4 kubelet: Flag --allow-privileged has been deprecated, will be removed in a future version
Apr 26 19:43:37 k8s-n4 kubelet: Flag --serialize-image-pulls has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 26 19:43:37 k8s-n4 kubelet: I0426 19:43:37.383491    8495 feature_gate.go:226] feature gates: &{{} map[]}
Apr 26 19:43:37 k8s-n4 systemd: Started Kubernetes systemd probe.
Apr 26 19:43:37 k8s-n4 systemd: Starting Kubernetes systemd probe.
Apr 26 19:43:37 k8s-n4 kubelet: W0426 19:43:37.388820    8495 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Apr 26 19:43:37 k8s-n4 kubelet: W0426 19:43:37.393559    8495 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
Apr 26 19:43:37 k8s-n4 kubelet: I0426 19:43:37.393648    8495 server.go:376] Version: v1.10.1
Apr 26 19:43:37 k8s-n4 kubelet: I0426 19:43:37.393723    8495 feature_gate.go:226] feature gates: &{{} map[]}
Apr 26 19:43:37 k8s-n4 kubelet: I0426 19:43:37.393839    8495 plugins.go:89] No cloud provider specified.
Apr 26 19:43:37 k8s-n4 kubelet: E0426 19:43:37.396495    8495 bootstrap.go:179] Unable to read existing bootstrap client config: invalid configuration: [unable to read client-cert /etc/kubernetes/ssl/kubelet-client.crt for default-auth due to open /etc/kubernetes/ssl/kubelet-client.crt: no such file or directory, unable to read client-key /etc/kubernetes/ssl/kubelet-client.key for default-auth due to open /etc/kubernetes/ssl/kubelet-client.key: no such file or directory]
Apr 26 19:44:37 k8s-n4 kubelet: F0426 19:44:37.509109    8495 server.go:233] failed to run Kubelet: timed out waiting for the condition
Apr 26 19:44:37 k8s-n4 systemd: kubelet.service: main process exited, code=exited, status=255/n/a
Apr 26 19:44:37 k8s-n4 systemd: Unit kubelet.service entered failed state.
Apr 26 19:44:37 k8s-n4 systemd: kubelet.service failed.
Apr 26 19:44:42 k8s-n4 systemd: kubelet.service holdoff time over, scheduling restart.
Apr 26 19:44:42 k8s-n4 systemd: Cannot add dependency job for unit firewalld.service, ignoring: Unit is masked.

**Comment by zjj2wry** [comment]
> 找到问题，我只要启动kubelet的时候 执行kubectl certificate approve 去接受 一下就好了，但是我不明白的是为啥我不接受，他会一直创建csr

因为启动的时候发现自己没有证书，就会创建一个 csr 请求，如果不想使用 kubectl approve，可以把证书的 controller 打开，自动 approve

**Comment by rootsongjc** [comment]
问题解决了吗？可以关闭Issue了吗？
