### ISSUE TITLE
nginx ingress controller 配置不成功

### ISSUE THREAD

**Issue by ghost** [rootsongjc/kubernetes-handbook#210]
## 环境

**版本和配置信息**

- kubernetes版本：1.9
- docker版本：17.12.1-ce
- 网络插件：flanneld
- 存储类型：

## 操作

根据nginx-ingress-controller.yaml配置nginx ingress后一直失败

## 日志

```bash
[root@k8s-master storageclass]# kubectl get pod -n seagoor-dev -o wide | grep nginx-ingress-controller
nginx-ingress-controller-s64n2            0/1       CrashLoopBackOff   6          6m        10.0.6.5      10.0.6.5

kubectl describe pod/nginx-ingress-controller-s64n2 -n seagoor-dev
Events:
  Type     Reason                 Age               From               Message
  ----     ------                 ----              ----               -------
  Normal   SuccessfulMountVolume  7m                kubelet, 10.0.6.5  MountVolume.SetUp succeeded for volume "nginx-ingress-serviceaccount-token-2dlqb"
  Warning  Unhealthy              6m (x5 over 7m)   kubelet, 10.0.6.5  Liveness probe failed: Get http://10.0.6.5:10254/healthz: dial tcp 10.0.6.5:10254: getsockopt: connection refused
  Normal   Pulled                 6m (x3 over 7m)   kubelet, 10.0.6.5  Container image "registry.cn-shanghai.aliyuncs.com/damon_k8s/nginx-ingress-controller:v0.9.0" already present on machine
  Normal   Created                6m (x3 over 7m)   kubelet, 10.0.6.5  Created container
  Normal   Killing                6m (x2 over 6m)   kubelet, 10.0.6.5  Killing container with id docker://nginx-ingress-controller:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Started                6m (x3 over 7m)   kubelet, 10.0.6.5  Started container
  Warning  Unhealthy              6m (x8 over 7m)   kubelet, 10.0.6.5  Readiness probe failed: Get http://10.0.6.5:10254/healthz: dial tcp 10.0.6.5:10254: getsockopt: connection refused
  Warning  BackOff                2m (x11 over 4m)  kubelet, 10.0.6.5  Back-off restarting failed container


[root@k8s-master storageclass]# kubectl logs pod/nginx-ingress-controller-s64n2 -n seagoor-dev
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    0.9.0-beta.19
  Build:      git-37a230c
  Repository: https://github.com/kubernetes/ingress-nginx
-------------------------------------------------------------------------------

I0508 06:07:24.219042       5 main.go:227] Creating API client for https://10.254.0.1:443
I0508 06:07:24.475432       5 main.go:239] Running in Kubernetes Cluster version v1.9 (v1.9.6) - git (clean) commit 9f8ebd171479bec0ada837d7ee641dec2f8c6dd1 - platform linux/amd64
I0508 06:07:24.509530       5 main.go:83] validated seagoor-dev/default-http-backend as the default backend
I0508 06:07:34.568593       5 stat_collector.go:77] starting new nginx stats collector for Ingress controller running in namespace  (class nginx)
I0508 06:07:34.568638       5 stat_collector.go:78] collector extracting information from port 18080
I0508 06:07:36.188853       5 nginx.go:250] starting Ingress controller
I0508 06:07:36.706131       5 nginx.go:255] running initial sync of secrets
I0508 06:07:36.706189       5 nginx.go:288] starting NGINX process...
I0508 06:07:36.724294       5 leaderelection.go:174] attempting to acquire leader lease...
I0508 06:07:36.853670       5 status.go:196] new leader elected: nginx-ingress-controller-zpjwd
I0508 06:07:36.879415       5 controller.go:211] backend reload required
I0508 06:07:36.879614       5 stat_collector.go:34] changing prometheus collector from  to default
I0508 06:07:43.407432       5 controller.go:220] ingress backend successfully reloaded...
I0508 06:07:43.435303       5 main.go:153] Received SIGTERM, shutting down
I0508 06:07:43.435325       5 nginx.go:333] shutting down controller queues
I0508 06:07:43.435344       5 nginx.go:341] stopping NGINX process...
2018/05/08 06:07:44 [notice] 24#24: signal process started
I0508 06:07:53.171983       5 nginx.go:354] NGINX process has stopped
I0508 06:07:53.172007       5 main.go:161] Handled quit, awaiting pod deletion
I0508 06:08:03.177456       5 main.go:164] Exiting with 0
```

这是什么原因

**Comment by lyc20140320** [comment]
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress-controller
  namespace: seagoor-dev
spec:
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
      annotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      hostNetwork: true
      containers:
        - name: nginx-ingress-controller
          image: registry.cn-shanghai.aliyuncs.com/damon_k8s/nginx-ingress-controller:v0.9.0
          args:
            - /nginx-ingress-controller
            - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
            - --configmap=$(POD_NAMESPACE)/nginx-configuration
            - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
            - --udp-services-configmap=$(POD_NAMESPACE)/udp-services
            - --annotations-prefix=nginx.ingress.kubernetes.io
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      nodeSelector:
        role: nginxplus

这是具体的yaml文件  @rootsongjc

**Comment by whmzsu** [comment]
把 配置文件里的 `initialDelaySeconds: 10`  时间改大一些，比如60，看日志像是liveness的probe检测不成功导致杀掉pod 容器的

**Comment by Erically** [comment]
解决了？
