### ISSUE TITLE
在一台node上做eureka集群

### ISSUE THREAD

**Issue by jamesalice123** [rootsongjc/kubernetes-handbook#211]
## 环境
centos7.4

**版本和配置信息**

- kubernetes版本：1.9
- docker版本：1.13
- 网络插件：flannel
- 存储类型：

## 操作
在一个节点起６个应用，其中３个应用为master，３个应用为slave,把他们的clusterip都映射到nodes

**导致该问题的操作或现象**
在浏览器访问应用时，没有出现master,slave两个集群，只有一个slave集群
## 日志

**日志或报错信息**

**Comment by rootsongjc** [comment]
“把他们的clusterip都映射到nodes”这句话是什么意思？你想问的问题是？

**Comment by jamesalice123** [comment]
@rootsongjc 就是他们要额eureka集群，一台master,一台slave，他们需要在/etc/host下写对方ip才能相互注册，所以我想到的就是把他们每个pod的service映射出来写到宿主机上
