### ISSUE TITLE
Influxdb deployment issue

### ISSUE THREAD

**Issue by jerryyanmj** [rootsongjc/kubernetes-handbook#218]
## 环境

**版本和配置信息**

- kubernetes版本：1.10
- docker版本：1.13
- 网络插件：flannel
- 存储类型：

## 操作
kubectl create -f inflexdb-deployment.yaml

**导致该问题的操作或现象**
Pod is created, but throwing error

## 日志

```bash
Error: failed to start container "influxdb": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:364: container init caused \"rootfs_linux.go:54: mounting \\\"/var/lib/kubelet/pods/e76b2d64-5a5e-11e8-b179-080027c9c16c/volumes/kubernetes.io~configmap/influxdb-config\\\" to rootfs \\\"/var/lib/docker/overlay2/e50b7f32607a04096a36d2d4852a7d6fdf4d73324ab447a2f780d8b1c7f8efb2/merged\\\" at \\\"/var/lib/docker/overlay2/e50b7f32607a04096a36d2d4852a7d6fdf4d73324ab447a2f780d8b1c7f8efb2/merged/etc/config.toml\\\" caused \\\"not a directory\\\"\"" : Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
````

**日志或报错信息**

**Comment by rootsongjc** [comment]
你用的是这个repo里的`influxdb-deployment.yaml`文件吗？

**Comment by jerryyanmj** [comment]
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        - mountPath: /etc/config.toml
          name: influxdb-config
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: influxdb-config
        configMap:
          name: influxdb-config

**Comment by jerryyanmj** [comment]
似乎得加上subPath: config.toml  现在工作了

**Comment by jerryyanmj** [comment]
`apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        - mountPath: /etc/config.toml
          subPath: config.toml
          name: influxdb-config
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: influxdb-config
        configMap:
          name: influxdb-config`

**Comment by jerryyanmj** [comment]
`
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        - mountPath: /etc/config.toml
          subPath: config.toml
          name: influxdb-config
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: influxdb-config
        configMap:
          name: influxdb-config
`
