### ISSUE TITLE
按照教程配置完成，flannel虚拟网络未能启用。

### ISSUE THREAD

**Issue by lovebaicai** [rootsongjc/kubernetes-handbook#219]
## 环境

**版本和配置信息**
- 系统版本：CentOS Linux release 7.3.1611 (Core)
- kubernetes版本：1.8
- docker版本：17.03.0-ce
- 网络插件：flannel
- 存储类型：未配置

## 操作

**导致该问题的操作或现象**
- 正常按照教程配置，未发现异常，服务启动正常。
 ![](http://7xnh53.com1.z0.glb.clouddn.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20180518153000.png)
![](http://7xnh53.com1.z0.glb.clouddn.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20180518152954.png)
![](http://7xnh53.com1.z0.glb.clouddn.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20180518153004.png)
![](http://7xnh53.com1.z0.glb.clouddn.com/WX20180518-153457.png)
![](http://7xnh53.com1.z0.glb.clouddn.com/WechatIMG975.jpeg)
## 日志

**日志或报错信息**
- 无异常log，或者报错信息（可能未找到异常信息位置）

**Comment by jerryyanmj** [comment]
建议你打印日志到文件。
1 - 在flannel service配置中加3行
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=flannel
2 - 在 /etc/rsyslog.d/建立flannel.conf
if $programname == 'flannel' then /var/log/kubernetes/flannel.log
if $programname == 'flannel' then ~
3 - systemctl restart rsyslog 和 flannel

**Comment by 372046933** [comment]
@jerryyanmj 是不是用journalctl --unit=flannel就可以了？ systemd好像用journalctl 查日志的

**Comment by 372046933** [comment]
这个问题我也出现了，顺便贴下flannel的启动日志
`May 21 17:50:16 ip-172-31-47-34 sudo[4256]:       lh : TTY=pts/1 ; PWD=/home/lh ; USER=root ; COMMAND=/usr/bin/systemctl start flanneld.service
May 21 17:50:16 ip-172-31-47-34 sudo[4256]: pam_unix(sudo:session): session opened for user root by lh(uid=0)
May 21 17:50:16 ip-172-31-47-34 systemd[1]: Starting Flanneld overlay address etcd agent...
May 21 17:50:16 ip-172-31-47-34 flanneld[4259]: I0521 17:50:16.616730    4259 main.go:475] Determining IP address of default interface
May 21 17:50:16 ip-172-31-47-34 flanneld[4259]: I0521 17:50:16.619121    4259 main.go:488] Using interface with name eth0 and address 172.31.47.34
May 21 17:50:16 ip-172-31-47-34 flanneld[4259]: I0521 17:50:16.619290    4259 main.go:505] Defaulting external address to interface address (172.31.47.34)
May 21 17:50:16 ip-172-31-47-34 flanneld[4259]: I0521 17:50:16.619484    4259 main.go:235] Created subnet manager: Etcd Local Manager with Previous Subnet: 10.1.30.0/24
May 21 17:50:16 ip-172-31-47-34 flanneld[4259]: I0521 17:50:16.619552    4259 main.go:238] Installing signal handlers
May 21 17:50:16 ip-172-31-47-34 flanneld[4259]: I0521 17:50:16.620778    4259 main.go:353] Found network config - Backend type: host-gw
May 21 17:50:16 ip-172-31-47-34 flanneld[4259]: I0521 17:50:16.622102    4259 local_manager.go:147] Found lease (10.1.30.0/24) for current IP (172.31.47.34), reusing
May 21 17:50:16 ip-172-31-47-34 flanneld[4259]: I0521 17:50:16.624851    4259 main.go:300] Wrote subnet file to /run/flannel/subnet.env
May 21 17:50:16 ip-172-31-47-34 flanneld[4259]: I0521 17:50:16.624933    4259 main.go:304] Running backend.
May 21 17:50:16 ip-172-31-47-34 flanneld[4259]: I0521 17:50:16.641575    4259 route_network.go:53] Watching for new subnet leases
May 21 17:50:16 ip-172-31-47-34 flanneld[4259]: I0521 17:50:16.642487    4259 main.go:396] Waiting for 22h59m59.979929055s to renew lease
May 21 17:50:16 ip-172-31-47-34 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=flanneld comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 21 17:50:16 ip-172-31-47-34 sudo[4256]: pam_unix(sudo:session): session closed for user root
May 21 17:50:16 ip-172-31-47-34 systemd[1]: Started Flanneld overlay address etcd agent.`

**Comment by 372046933** [comment]
再补一条日志，这个是直接不带参数的运行
`sudo /usr/bin/flanneld
I0521 18:01:28.568901    4694 main.go:475] Determining IP address of default interface
I0521 18:01:28.569373    4694 main.go:488] Using interface with name eth0 and address 172.31.47.34
I0521 18:01:28.569495    4694 main.go:505] Defaulting external address to interface address (172.31.47.34)
I0521 18:01:28.569776    4694 main.go:235] Created subnet manager: Etcd Local Manager with Previous Subnet: 10.1.30.0/24
I0521 18:01:28.569838    4694 main.go:238] Installing signal handlers
I0521 18:01:28.571332    4694 main.go:353] Found network config - Backend type: host-gw
I0521 18:01:28.572653    4694 local_manager.go:147] Found lease (10.1.30.0/24) for current IP (172.31.47.34), reusing
I0521 18:01:28.573532    4694 main.go:300] Wrote subnet file to /run/flannel/subnet.env
I0521 18:01:28.573594    4694 main.go:304] Running backend.
I0521 18:01:28.578656    4694 route_network.go:53] Watching for new subnet leases
I0521 18:01:28.579352    4694 main.go:396] Waiting for 22h59m59.993599285s to renew lease

`

**Comment by lovebaicai** [comment]
@rootsongjc 已经在群里回答了这个问题。如果你配置的是vxlan，是能看到flannel的bridge。因为我配置的是host-gw使用的直接路由，所以没有flannel。
- vxlan：vxlan封装，需要配置VNI，Port（默认8472）和GBP
- host-gw：直接路由的方式，将容器网络的路由信息直接更新到主机的路由表中，仅适用于二层直接可达的网络
- 参考：
  - [CNCF CNI系列之四：flannel host-gw模式工作原理浅析
](https://blog.csdn.net/cloudvtech/article/details/79809569)
  - [Flannel原理
](https://feisky.gitbooks.io/sdn/container/flannel/)

**Comment by 372046933** [comment]
@lovebaicai 感谢！还有个问题，`ip route`看不到flannel的路由表，只有默认主机路由和docker路由，这个咋整？
