### ISSUE TITLE
关于节点扩容两个问题（证书+网络）

### ISSUE THREAD

**Issue by lovebaicai** [rootsongjc/kubernetes-handbook#223]
@rootsongjc ，超哥，关于节点扩容，有两个问题，您如果有自己的实践，请您帮忙解答下。
- 证书问题：有两个朋友提出了证书问题，@eagleyinfz [https://github.com/rootsongjc/kubernetes-handbook/issues/215](https://github.com/rootsongjc/kubernetes-handbook/issues/215)，@amwuqd [https://github.com/rootsongjc/kubernetes-handbook/issues/186](https://github.com/rootsongjc/kubernetes-handbook/issues/186)。
- 网络问题：目前flannel网络配置也是需要在部署的时候确认好节点ip，[#安装flannel网络插件
](https://jimmysong.io/kubernetes-handbook/practice/flannel-installation.html)那么后续在扩容的时候，这个网络服务是需要停止，然后重新配置节点ip来扩容吗？

**Comment by rootsongjc** [comment]
**证书问题**
很多用户在添加主机前，先增加的主机的IP必须在证书文件中

**网络问题**
flannel配置里只要指定了etcd的IP就行了，每个节点上的flannel的配置是一样的

**Comment by lovebaicai** [comment]
@rootsongjc ，那就是说证书一定要提前生成，否则后续是无法添加节点的。超哥，是这个意思吗？

**Comment by rootsongjc** [comment]
是的，新节点的证书需要提前生成。

**Comment by lovebaicai** [comment]
@rootsongjc ，超哥，有其他解决方案吗？
如果这样的话，就不算是动态扩容了。后续如果规划有问题，这样就没办法直接增加节点了。

**Comment by lovebaicai** [comment]
- 可能因为本人操作问题
- 按照超哥教程，参考这个教程[https://github.com/gjmzj/kubeasz](https://github.com/gjmzj/kubeasz)，和这个[手动搭建高可用的kubernetes 集群
](https://blog.qikqiak.com/post/manual-install-high-available-kubernetes-cluster/)
- 部署完成可动态扩容，node节点证书可直接通过 kublet 的 TLS 证书请求来生成
- @rootsongjc 感谢超哥。

**Comment by ZQshark** [comment]
如果我在证书的hosts里面指定网段，是否可以？
