### ISSUE TITLE
kube-proxy启动时报错，proxy工作不正常

### ISSUE THREAD

**Issue by qhme** [rootsongjc/kubernetes-handbook#227]
## 环境

**版本和配置信息**

- kubernetes版本：1.8.13
- docker版本：1.13.1
- 网络插件：flannel
- 存储类型：

## 操作
systemctl start kube-proxy
**导致该问题的操作或现象**
proxy工作不正常，kube-dns不能启动
## 日志
Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed）
**日志或报错信息**

**Comment by rootsongjc** [comment]
`Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed）`看这条错误，是不是你的初始环境没配好。

**Comment by jesse1993** [comment]
问题解决了吗？可否分享一下解决方案？

**Comment by chen-joe1015** [comment]
我们遇到同样的问题，如果解决了能否告知，感谢！

**Comment by rootsongjc** [comment]
有更详细的配置和报错说明吗？

**Comment by kobehaha** [comment]
iptables是否安装，能否正常工作呢？

**Comment by rootsongjc** [comment]
@jesse1993 你的防火墙关闭了吗？iptables安装是否正确？使用的是什么操作系统？版本是？

**Comment by skymyyang** [comment]
你好~我也遇到了跟你一样的问题，现在我将kube-proxy的由ipvs改为iptables，才能正常连接service，请问你是怎么解决的？？

**Comment by LinQing2017** [comment]
情况和楼主类似，kube-proxy使用iptables的时候service ip死活无法访问，换成ipvs就好了！我是在centos7,上装的1.13

**Comment by kobehaha** [comment]
我也遇到类似的问题，然后换了更高的k8s版本就可以了,看官方说是一个 iptables版本对应的bugs
