### ISSUE TITLE
提一个建议，在部署node节点这个页面

### ISSUE THREAD

**Issue by moocherabc** [rootsongjc/kubernetes-handbook#229]
页面地址：https://jimmysong.io/kubernetes-handbook/practice/node-installation.html#

`kubelet 启动时向 kube-apiserver 发送 TLS bootstrapping 请求，需要先将 bootstrap token 文件中的 kubelet-bootstrap 用户赋予 system:node-bootstrapper cluster 角色(role)， 然后 kubelet 才能有权限创建认证请求(certificate signing requests)：`
这一段下面的命令是master节点执行的.. 麻烦注明下...
```
cd /etc/kubernetes
kubectl create clusterrolebinding kubelet-bootstrap \
  --clusterrole=system:node-bootstrapper \
  --user=kubelet-bootstrap
```

然后再将/etc/kubernetes/bootstrap.kubeconfig 拷贝到, node节点上 `/etc/kubernetes/`  下  启动后才能成功的发送crs请求...

k8s版本 1.10.2

**Comment by rootsongjc** [comment]
感谢您的建议，如果方便的话可以可以提交一个PR进行更改。

**Comment by rootsongjc** [comment]
文档已经补充，关闭该Issue。
