### ISSUE TITLE
centos7.5中Permission 0644 for .ssh/id_rsa Are Too Open降权限为600还是一样报644错误

### ISSUE THREAD

**Issue by jamesalice123** [rootsongjc/kubernetes-handbook#236]
## 环境  centos7.5

**版本和配置信息**

- kubernetes版本：
- docker版本：
- 网络插件：
- 存储类型：

## 操作

**导致该问题的操作或现象**

## 日志        

centos7.5中Permission 0644 for .ssh/id_rsa Are Too Open降权限为600还是一样报644错误

**日志或报错信息**

**Comment by rootsongjc** [comment]
具体报什么错误？你确定没改错文件？

**Comment by jamesalice123** [comment]
问题：Permissions 0644 for '/root/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/root/.ssh/id_rsa": bad permissions
root@192.168.108.130's password: 
Permission denied, please try again.
============================================
没有改错，我是用了命令   chmod  600  /root/.ssh/id_rsa   ,而且我看到权限也降低了，但是再次执行脚本还是出来上面这个错误，我输入root密码后就卡住了
@rootsongjc

**Comment by whmzsu** [comment]
这个改权限是改本机的，不是远端节点的，是否有改错？？？

**Comment by jamesalice123** [comment]
好的，明白了
