### ISSUE TITLE
kube-prometheus安装过程的疑问

### ISSUE THREAD

**Issue by jamesalice123** [rootsongjc/kubernetes-handbook#239]
## 环境

**版本和配置信息**

- kubernetes版本： 1.10.4
- docker版本：17.03.2
- 网络插件：flanneld
- 存储类型：
## 操作
https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus
**导致该问题的操作或现象**
按照readme所示，是否需要安装manifests/下的所有yaml文件呢，后面的文档内容看不懂了

## 日志

**日志或报错信息**

**Comment by rootsongjc** [comment]
这个我还没看过，现在没办法回答你。
