### ISSUE TITLE
排版可能有问题

### ISSUE THREAD

**Issue by zhangx501** [rootsongjc/kubernetes-handbook#25]
4.1.4 安装kubectl命令行工具 ，但实际上 4.1.2 创建kubeconfig文件 中 创建 kubelet bootstrapping kubeconfig 文件时需要使用命令 kubectl config set 是否要讲第四小节提前？

**Comment by rootsongjc** [comment]
感谢您的建议。
已在文章开头增加安装kubectl的提醒。
