### ISSUE TITLE
期望添加gogs以及与jenkins的整合教程

### ISSUE THREAD

**Issue by dreamingo88** [rootsongjc/kubernetes-handbook#253]
期望添加gogs（git仓库，跟github类似）的安装，以及与jenkins整合进行自动化部署的教程。谢谢！

**Comment by rootsongjc** [comment]
你好，感谢你的建议，gogs的安装很简单，但是Jenkins太重太麻烦，我希望用更简洁的方式做持续集成和发布。也希望大家可以一起来完善CI/CD部分的文档。
