### ISSUE TITLE
K8S组件全部正常，但是所有pod无法正常启动

### ISSUE THREAD

**Issue by Jiangxiaobin** [rootsongjc/kubernetes-handbook#257]
## 环境

**版本和配置信息**

- kubernetes版本：**1.9.7**
- docker版本：**docker-17.12.1-ce**
- 网络插件：**flannel-0.7.1**
- 存储类型：**未设置**

## 操作

**导致该问题的操作或现象**

将flannel方案换成了calico方案，发现各种报错，所以想退回到flannel方案，所有配置信息都重置回原来的状态，并且master和node上的所有组件全部重启了，所有组件正常（包括kube-controller-manager、kube-scheduler、kube-apiserver、docker、etcd、flannel），但是所有的pod都起不来。

进入node宿主机，使用docker ps -a看到所有的container都是exited状态，或者是createing状态，如果手动docker start containerID的话，会报如下错误：

failed to create endpoint **endPointName** on network bridge: failed to add the host **(veth237cf33)** <=> sandbox **(vethe214e84)** pair interfaces: operation not supported
Error: failed to start containers: 996bf24b065b

## 日志

**日志或报错信息**

failed to create endpoint **endPointName** on network bridge: failed to add the host **(veth237cf33)** <=> sandbox **(vethe214e84)** pair interfaces: operation not supported

**Comment by rootsongjc** [comment]
不知你的flannel是什么方式安装的？flannel启动有什么错误信息？
