### ISSUE TITLE
kubeconfig成功创建，但是无法对集群进行操作

### ISSUE THREAD

**Issue by CalbeeMing0530** [rootsongjc/kubernetes-handbook#264]
## 环境

**版本和配置信息**

- kubernetes版本：v1.11
- docker版本：18.06.0-ce
- 网络插件：flannel
- 存储类型：未设置
- linux版本：Ubuntu 16.04
- kubernetes集群节点：node3（master） node4

## 操作

**导致该问题的操作或现象**

按照jimmy老师文档操作安装kubeconfig文件
**文档链接：**
 https://jimmysong.io/kubernetes-handbook/guide/kubectl-user-authentication-authorization.html
 https://jimmysong.io/kubernetes-handbook/practice/create-tls-and-secret-key.html

**截图所示：**
![0643c37c71bb7e00a4b11661b16f81f](https://user-images.githubusercontent.com/40563405/43893221-b93536e0-9c00-11e8-8170-abbd0376fdf9.png)
![ea7879be857c3881e4ed0c5fd6c2c6e](https://user-images.githubusercontent.com/40563405/43893232-bb5e37aa-9c00-11e8-8e63-00d9fe3a5629.png)
![223151d10e99df304dcdd5067cd030c](https://user-images.githubusercontent.com/40563405/43893237-be666f44-9c00-11e8-824e-bbb6706b8c17.png)
![902b7c8203a331578a26a6cb1dbfc53](https://user-images.githubusercontent.com/40563405/43893242-c19666d8-9c00-11e8-9e6d-4a12c55d4413.png)
![45433ff8cf8b9e9bb18f6cf01b6bec4](https://user-images.githubusercontent.com/40563405/43893243-c41275fa-9c00-11e8-8bf4-0f92cf0e7ad2.png)

**自己认为是否这步出现了错误?**

原文档截图：
![image](https://user-images.githubusercontent.com/40563405/43893304-0eb4b2b2-9c01-11e8-9f2f-ffc45f8e5c28.png)

我的截图：
![image](https://user-images.githubusercontent.com/40563405/43893363-3f52c0f8-9c01-11e8-9cb9-2892f5e58282.png)

## 日志

**日志或报错信息**

最后报错信息为Unable to connect to the server: x509: certificate signed by unknown authority

**Comment by rootsongjc** [comment]
应该是在创建用户的时候出错了吧，另外你使用kubectl操作peter的namespace的时候没有用`-n peter`来指定namespace。

**Comment by CalbeeMing0530** [comment]
我试了加-n peter，但还是报那个错误，会不会创建Peter时生成的证书有问题? 我是按教程一步一步来的，我试着将$HOME/.kube/config替换为peter.kubeconfig，然后kubectl get po -n peter就报错了，等我切换回之前的config，就可以正常显示了（在创建peter.kubeconfig之后，还没有切换peter.kubeconfig之前我在peter namespace创建了nginx的deployment作为测试），如下图所示：
![a7e02c9f3556914be5039bafb8c091f](https://user-images.githubusercontent.com/40563405/43905030-bb948874-9c22-11e8-9d50-3366d5d5908d.png)

查看了下绑定的信息如下图：
![image](https://user-images.githubusercontent.com/40563405/43905080-d5821c42-9c22-11e8-8442-b6a9f1637735.png)

创建用户是使用的create-user.sh这个脚本，您的意思时创建用户时候出错了？能给点提示吗？或是需要什么信息，我可以提供出来，非常感谢！ @rootsongjc
