### ISSUE TITLE
HPA相关问题

### ISSUE THREAD

**Issue by hechuan73** [rootsongjc/kubernetes-handbook#275]
您好，我现在在做自定义metrics的HPA实验，看了您HPA目录下的几个文件，有几个问题想要请教一下：

1. 使用custom-metrics.yaml应该是可以创建custom metrics API，我准备参照您的写一份，其中涉及到的镜像使用的你自己的仓库，目前我们应该是可以从你仓库拉镜像吧？因为看到中文指南上说要改成自己的仓库，所以想问一下。

2. 您这有prometheus-operator.yaml和sample-prometheus-instance.yaml两个文件，应该都是启动prometheus的吧？是需要都执行还是执行其中一个？因为看到custom-metrics中的配置，好像是用的后者，所以想请教下。

**Comment by rootsongjc** [comment]
1. 你需要使用自己镜像仓库，我的镜像仓库你是访问不里的。
2. Prometheus的配置有些问题，我还没修复。

**Comment by hechuan73** [comment]
@rootsongjc 好的，谢谢！
