### ISSUE TITLE
Question: is there an english version too?

### ISSUE THREAD

**Issue by DanyC97** [rootsongjc/kubernetes-handbook#289]
Hi,

Not a mandarin speaker however i managed to use google translate and found the info very useful. As such my question to you is if there is an English version too or you planning to have one ? 

thanks and great handbook, it flows so nicely.

**Comment by rootsongjc** [comment]
There is no English version yet. If you have any question, you can touch me https://jimmysong.io/about/

**Comment by DanyC97** [comment]
excellent, much thanks @rootsongjc !
