### ISSUE TITLE
kube-dns启动失败

### ISSUE THREAD

**Issue by denkensk** [rootsongjc/kubernetes-handbook#29]
kubernetes版本是1.7.2，按照 http://rootsongjc.github.io/blogs/kubernetes-kubedns-installation/ 这个文档配置的。
RBAC和sa都有
<img width="735" alt="machi 2017-08-11 17-23-42" src="https://user-images.githubusercontent.com/8958057/29207769-f463f14e-7eb9-11e7-91ca-ca5ff063596a.png">
![image](https://user-images.githubusercontent.com/8958057/29207621-806a31cc-7eb9-11e7-873b-54a9e9104fe1.png)

但是在启动dns容器的时候容器日志报错
![image](https://user-images.githubusercontent.com/8958057/29207519-0a6e87a2-7eb9-11e7-9a7b-a29c4f866ca5.png)

**Comment by rootsongjc** [comment]
从错误日志来看还是 `serviceAccount` 配置有问题。
