### ISSUE TITLE
harbor 打tag可否设置免library

### ISSUE THREAD

**Issue by bo8888** [rootsongjc/kubernetes-handbook#298]
现在  docker push 172.16.8.100/library/aaaa:1.0
可以push上去
是因为有library这个项目
请问可否像docker hub 那样省略 library
就像docker pull nginx 其实是docker pull library/nginx

**Comment by rootsongjc** [comment]
这个一个与Kubernetes本身无关的问题，建议到[Harbor社区](https://github.com/goharbor/harbor)问一下，library是默认的配置，应该是可以修改的。

**Comment by bo8888** [comment]
谢谢
