### ISSUE TITLE
部署出来的flannel网络和docker0的网络MTU不一致，可能导致网络性能变差

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/kubernetes-handbook#30]
容器、docker0、flannel这三者MTU一致，如果使用VXLAN的话为1450，然后再加上vxlan的封装，MTU1500，这个时候node节点的网卡1500就刚好，直接转发了。
请检查flannel和node节点配置

**Comment by epiclen** [comment]
请教宋总 之前使用1.5.2版本出现集群内pod通过clusterip/host访问偶尔出现超时，但是pod通过nodeip nodeport访问无超时现象，是否与mtu不一致有关 谢谢🙏

**Comment by rootsongjc** [comment]
你现在用的是kubernetes和flannel是什么版本？flannel用的是什么模式？你这个问题比较复杂。
