### ISSUE TITLE
部署node节点步骤补充

### ISSUE THREAD

**Issue by Paul-Xiong** [rootsongjc/kubernetes-handbook#304]
## 环境

**版本和配置信息**

- kubernetes版本：1.12.0
- docker版本：18.06.0-ce
- 网络插件：
- 存储类型：

## 操作

**导致该问题的操作或现象**
按照“部署node节点”的文档注册节点报错如下：
![image](https://user-images.githubusercontent.com/16216658/48048287-fafd7b80-e1d5-11e8-8081-7d1fc3f9ba97.png)
后来翻看以往的issue，找到已关闭的相同问题issue #98
原因是还缺少一个角色，如下创建角色即可
```
kubectl create clusterrolebinding kubelet-nodes --clusterrole=system:node --group=system:nodes
```
所以我希望宋总能把这创建角色的步骤添加到“部署node节点”文档中，避免今后搭建环境的同志们碰到相同的问题。
## 日志

**日志或报错信息**

**Comment by rootsongjc** [comment]
@Paul-Xiong 能直接提个 PR 加上这个描述吗？谢谢。

**Comment by Paul-Xiong** [comment]
> @Paul-Xiong 能直接提个 PR 加上这个描述吗？谢谢。

可以的
