### ISSUE TITLE
etcd API版本3和2的问题

### ISSUE THREAD

**Issue by ghost** [rootsongjc/kubernetes-handbook#308]
etcd安装的版本是3.2.22
etcd有两个api版本v2和v3
v2的etcdctl有mk命令可以创建目录，比如flanneld的配置目录
但是v3的etcdctl没有相关的命令？

**Comment by pengjinyi2017** [comment]
![image](https://user-images.githubusercontent.com/27040580/48246367-2d071b80-e42a-11e8-85b4-3b28f3082351.png)
![image](https://user-images.githubusercontent.com/27040580/48246397-3f815500-e42a-11e8-9a46-0d45050360e1.png)

**Comment by listen-lavender** [comment]
who can help
