### ISSUE TITLE
Heapster 在 kubelet 启动 https 之后会报错

### ISSUE THREAD

**Issue by LeoYang90** [rootsongjc/kubernetes-handbook#316]
## 环境

**版本和配置信息**

- kubernetes版本：1.11
- docker版本：18.09.0
- 网络插件：flannel
- 存储类型：

## 操作

按照 handbook 中的步骤安装 Heapster，会报错：

```
Error in scraping containers from kubelet:192.168.113.39:10255: failed to get all container stats from Kubelet URL "http://192.168.113.39:10255/stats/container/": Post http://192.168.113.39:10255/stats/container/: dial tcp 192.168.113.39:10255: getsockopt: connection refused
```

**导致该问题的操作或现象**

原因是 kubelet 启用了 https，因此需要在 heapster.yaml中：
```
- --source=kubernetes:https://kubernetes.default
```
修改为
```
- --source=kubernetes:https://kubernetes.default?kubeletHttps=true&kubeletPort=10250&insecure=true
```
## 日志

**日志或报错信息**

![image](https://user-images.githubusercontent.com/16485583/49231613-48fc4c80-f42d-11e8-9b17-3191ac10d14a.png)

**Comment by rootsongjc** [comment]
现在推荐的是使用 metric-server
