### ISSUE TITLE
输入错误.5.10.2

### ISSUE THREAD

**Issue by shaohongwu** [rootsongjc/kubernetes-handbook#320]
你好，在文档的 **使用Drone进行持续构建与发布** 章节，有一个输入错误，docker-compoe.yaml，应该应该是 docker-compose.yaml。
Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?
        Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by rootsongjc** [comment]
@shaohongwu 感谢指正，已修正。
