### ISSUE TITLE
kube-apiserver启动配置报错

### ISSUE THREAD

**Issue by InnocenceLee** [rootsongjc/kubernetes-handbook#322]
## 环境

**版本和配置信息**

- kubernetes版本：1.13
- docker版本：18.09.0
- 网络插件：flannel
- 存储类型：

## 操作
启动kube-apiserver报错
![image](https://user-images.githubusercontent.com/22140396/50272733-a1929880-0473-11e9-9076-5f103b9f3101.png)
**导致该问题的操作或现象**
配置报错，但是不知道具体哪个配置。
配置一：/k8s/kubernetes/cfg/kube-apiserver
![image](https://user-images.githubusercontent.com/22140396/50272807-e1f21680-0473-11e9-9aa7-961a5bf0bef7.png)
配置二：/usr/lib/systemd/system/kube-apiserver.service
![image](https://user-images.githubusercontent.com/22140396/50272829-f1715f80-0473-11e9-8073-be778f09e448.png)

麻烦大佬帮忙看看，感激不尽。

**Comment by rootsongjc** [comment]
图1里显示配置错误，你看看 kube-apiserver 启动的时候到底加载的是什么配置。

**Comment by InnocenceLee** [comment]
![image](https://user-images.githubusercontent.com/22140396/50273408-950f3f80-0475-11e9-9567-e77c91340312.png)
老师您好，启动日志只有这些。

**Comment by charlesren** [comment]
遇到类似问题，请检查TLS Bootstrapping Token 文件内容。

去掉如下例子里的双引号试试。
02b50b05283e98dd0fd71db496ef01e8,kubelet-bootstrap,10001,"system:bootstrappers"
正确格式为：
02b50b05283e98dd0fd71db496ef01e8,kubelet-bootstrap,10001,system:bootstrappers

当只有一个组时，不需要加引号。

**Comment by rootsongjc** [comment]
@charlesren 感谢反馈，如果需要更新文档增加一个说明可以提交个 PR，如果该问题已解决可以关闭该 issue。

**Comment by rootsongjc** [comment]
文档已更新。

**Comment by hanhui8220** [comment]
我把  token.csv 里面的引号去掉了，还是不行，请问楼主解决了吗
