### ISSUE TITLE
redhat系统下，dashboard插件需要额外下载image

### ISSUE THREAD

**Issue by cp542524698** [rootsongjc/kubernetes-handbook#33]
redhat7.2 系统；
需要下载pod-infrastructure：
# docker pull registry.access.redhat.com/rhel7/pod-infrastructure:latest

**Comment by rootsongjc** [comment]
为什么说还需要下载这个镜像呢？这个基础镜像应该在 `/etc/kubernetes/kubelet` 文件的 `KUBELET_POD_INFRA_CONTAINER` 变量中定义。

**Comment by cp542524698** [comment]
@rootsongjc 是的，后来找到了；
