### ISSUE TITLE
kubelet的配置里这段描述有问题

### ISSUE THREAD

**Issue by Jacky-fe** [rootsongjc/kubernetes-handbook#34]
“--cluster-domain 指定 pod 启动时 /etc/resolve.conf 文件中的 search domain ，起初我们将其配置成了 cluster.local，这样在解析 service 的 DNS 名称时是正常的，可是在解析 headless service 中的 FQDN pod name 的时候却错误，因此我们讲其修改为 cluster.local，可以解决该问题，关于 kubernetes 中的域名/服务名称解析请参见我的另一篇文章。”

cluster.local修改成cluster.local好没变化，看着有点晕

**Comment by rootsongjc** [comment]
笔误，漏了个点，一开始配置成了 `--cluster-domain=cluster.local.`，后来将最后的点去掉了。
