### ISSUE TITLE
Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by yewenchuan1688** [rootsongjc/kubernetes-handbook#35]
参照https://github.com/rootsongjc/follow-me-install-kubernetes-cluster  安装。

**操作系统**
```
[root@k8s-master ~]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
[root@k8s-master ~]# uname -a
Linux k8s-master 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**k8s集群环境**
```
curl https://10.x.x.x:6443/version --cert /etc/kubernetes/ssl/kubernetes.pem --key /etc/kubernetes/ssl/kubernetes-key.pem --cacert /etc/kubernetes/ssl/ca.pem
{
  "major": "1",
  "minor": "6",
  "gitVersion": "v1.6.0",
  "gitCommit": "fff5156092b56e6bd60fff75aad4dc9de6b6ef37",
  "gitTreeState": "clean",
  "buildDate": "2017-03-28T16:24:30Z",
  "goVersion": "go1.7.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**etcd**
```
etcdctl \
>   --ca-file=/etc/kubernetes/ssl/ca.pem \
>   --cert-file=/etc/kubernetes/ssl/kubernetes.pem \
>   --key-file=/etc/kubernetes/ssl/kubernetes-key.pem \
>   cluster-health
member 33ceb5b56308b8c4 is healthy: got healthy result from https://10.x.x.207:2379
member afb729f70db7c609 is healthy: got healthy result from https://10.x.x.206:2379
member c21f03a4f502d11a is healthy: got healthy result from https://10.x.x.208:2379
cluster is healthy
```

**问题**
```
[root@k8s-master ~]# kubectl get componentstatuses
Unable to connect to the server: x509: certificate signed by unknown authority
```

**Comment by yewenchuan1688** [comment]
[root@k8s-master ssl]# openssl verify -CAfile ca.pem kubernetes.pem 
kubernetes.pem: OK
[root@k8s-master ssl]# openssl verify -CAfile ca.pem kube-proxy.pem 
kube-proxy.pem: OK
[root@k8s-master ssl]# openssl verify -CAfile ca.pem admin.pem 
admin.pem: OK

**Comment by yewenchuan1688** [comment]
/etc/kubernetes/apiserver 配置
KUBE_API_ARGS="--authorization-mode=RBAC --runtime-config=rbac.authorization.k8s.io/v1beta1 --kubelet-https=true --experimental-bootstrap-token-auth --token-auth-file=/etc/kubernetes/token.csv --service-node-port-range=30000-32767 --tls-cert-file=/etc/kubernetes/ssl/kubernetes.pem --tls-private-key-file=/etc/kubernetes/ssl/kubernetes-key.pem --client-ca-file=/etc/kubernetes/ssl/ca.pem --service-account-key-file=/etc/kubernetes/ssl/ca-key.pem --etcd-cafile=/etc/kubernetes/ssl/ca.pem --etcd-certfile=/etc/kubernetes/ssl/kubernetes.pem --etcd-keyfile=/etc/kubernetes/ssl/kubernetes-key.pem --enable-swagger-ui=true --apiserver-count=3 --audit-log-maxage=30 --audit-log-maxbackup=3 --audit-log-maxsize=100 --audit-log-path=/var/lib/audit.log --event-ttl=1h"

**Comment by yewenchuan1688** [comment]
[root@k8s-master ssl]# cat /etc/kubernetes/token.csv
4b7ce34c2e85b68aacbac758ef492fa7,kubelet-bootstrap,10001,"system:kubelet-bootstrap"

**Comment by yewenchuan1688** [comment]
[root@k8s-master ssl]# journalctl -xef -u kubelet
-- Logs begin at 三 2017-08-16 02:59:44 CST. --
8月 16 03:00:04 k8s-master systemd[1]: Started Kubernetes Kubelet Server.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is done.
8月 16 03:00:04 k8s-master systemd[1]: Starting Kubernetes Kubelet Server...
-- Subject: Unit kubelet.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has begun starting up.
8月 16 03:00:05 k8s-master kubelet[2680]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
8月 16 03:00:05 k8s-master kubelet[2680]: I0816 03:00:05.138984    2680 feature_gate.go:144] feature gates: map[]
8月 16 03:00:05 k8s-master kubelet[2680]: error: failed to run Kubelet: cannot create certificate signing request: User "kubelet-bootstrap" cannot create certificatesigningrequests.certificates.k8s.io at the cluster scope. (post certificatesigningrequests.certificates.k8s.io)
8月 16 03:00:05 k8s-master systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
8月 16 03:00:05 k8s-master systemd[1]: Unit kubelet.service entered failed state.
8月 16 03:00:05 k8s-master systemd[1]: kubelet.service failed.

**Comment by rootsongjc** [comment]
https://github.com/rootsongjc/follow-me-install-kubernetes-cluster这个项目造就停止更新了，所有的额更改都在本项目中，你看到的可能是过时的配置，请先参考本项目中的安装部署说明。
PS. 提交Issue时应该注意下Markdown的格式化。

**Comment by Tangxzh317** [comment]
这个原因是由于ca证书不被本机信任导致的，只要把ca证书导入本地信任中心即可：

**Comment by Tangxzh317** [comment]
这个错误是由于自建的ca证书不被本机信任导致的，只要把ca证书导入到本地信任中心即可。具体只要在每个主机主机上运行一下：`cat ca证书文件 >> /etc/pki/tls/certs/ca-bundle.crt` 即可。

**Comment by yewenchuan1688** [comment]
问题解决了，应该是忘记了创建 kubectl kubeconfig 文件导致。

$ export KUBE_APISERVER="https://172.20.0.113:6443"
$ # 设置集群参数
$ kubectl config set-cluster kubernetes \
  --certificate-authority=/etc/kubernetes/ssl/ca.pem \
  --embed-certs=true \
  --server=${KUBE_APISERVER}
$ # 设置客户端认证参数
$ kubectl config set-credentials admin \
  --client-certificate=/etc/kubernetes/ssl/admin.pem \
  --embed-certs=true \
  --client-key=/etc/kubernetes/ssl/admin-key.pem
$ # 设置上下文参数
$ kubectl config set-context kubernetes \
  --cluster=kubernetes \
  --user=admin
$ # 设置默认上下文
$ kubectl config use-context kubernetes

**Comment by yewenchuan1688** [comment]
[root@k8s-master ssl]# kubectl get componentstatuses
NAME                 STATUS      MESSAGE                                                                                        ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection refused   
controller-manager   Healthy     ok                                                                                             
etcd-0               Healthy     {"health": "true"}                                                                             
etcd-1               Healthy     {"health": "true"}                                                                             
etcd-2               Healthy     {"health": "true"}                                                                             
1.
[root@k8s-master ssl]# cat /etc/kubernetes/controller-manager
###
# The following values are used to configure the kubernetes controller-manager

# defaults from config and apiserver should be adequate

# Add your own!
KUBE_CONTROLLER_MANAGER_ARGS="--address=127.0.0.1 --service-cluster-ip-range=10.250.0.0/16 --cluster-name=kubernetes --cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem --cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem  --service-account-private-key-file=/etc/kubernetes/ssl/ca-key.pem --root-ca-file=/etc/kubernetes/ssl/ca.pem --leader-elect=true"
2。
[root@k8s-master ssl]# cat /etc/kubernetes/scheduler
###
# kubernetes scheduler config

# default config should be adequate

# Add your own!
KUBE_SCHEDULER_ARGS="--leader-elect=true --address=127.0.0.1"

why？scheduler is Unhealthy.

**Comment by yewenchuan1688** [comment]
[root@k8s-master ssl]# kubectl get componentstatuses
NAME                 STATUS      MESSAGE                                                                                        ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection refused   
controller-manager   Healthy     ok                                                                                             
etcd-0               Healthy     {"health": "true"}                                                                             
etcd-1               Healthy     {"health": "true"}                                                                             
etcd-2               Healthy     {"health": "true"}                                                                             
[root@k8s-master ssl]# cat /etc/kubernetes/controller-manager
###
# The following values are used to configure the kubernetes controller-manager

# defaults from config and apiserver should be adequate

# Add your own!
KUBE_CONTROLLER_MANAGER_ARGS="--address=127.0.0.1 --service-cluster-ip-range=10.250.0.0/16 --cluster-name=kubernetes --cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem --cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem  --service-account-private-key-file=/etc/kubernetes/ssl/ca-key.pem --root-ca-file=/etc/kubernetes/ssl/ca.pem --leader-elect=true"
[root@k8s-master ssl]# cat /etc/kubernetes/scheduler
###
# kubernetes scheduler config

# default config should be adequate

# Add your own!
KUBE_SCHEDULER_ARGS="--leader-elect=true --address=127.0.0.1"
