### ISSUE TITLE
文章勘误 - 当前支持的CRI后端

### ISSUE THREAD

**Issue by zeromake** [rootsongjc/kubernetes-handbook#358]
## 文章勘误
[当前支持的CRI后端](https://github.com/rootsongjc/kubernetes-handbook/blob/master/concepts/cri.md#%E5%BD%93%E5%89%8D%E6%94%AF%E6%8C%81%E7%9A%84cri%E5%90%8E%E7%AB%AF)

`rkt：由于CoreOS主推的用来跟docker抗衡的容器运行时`

这句话的 `由于` 感觉有点怪，应该是 `由CoreOS主推` 吧。

**Comment by rootsongjc** [comment]
@zeromake 确实是笔误，请直接提交 PR 修整下吧，谢谢。
