### ISSUE TITLE
sercret文件没有挂载到容器

### ISSUE THREAD

**Issue by denkensk** [rootsongjc/kubernetes-handbook#37]
k8s版本:1.7.2
docker: 1.11.2
内核：3.10
docker驱动：devicemapper

容器里边没有文件显示
![image](https://user-images.githubusercontent.com/8958057/29407534-4883d8ae-8377-11e7-9da4-f5c763966d3e.png)
但是容器inspect显示已经挂载上了
![2](https://user-images.githubusercontent.com/8958057/29407757-1f676dae-8378-11e7-9d20-d2c745e48d29.jpg)
但是宿主机上显示有这个文件
![3](https://user-images.githubusercontent.com/8958057/29407764-24e8ba44-8378-11e7-9359-64db19682b81.jpg)

**Comment by rootsongjc** [comment]
这个问题已经有段时日了，现在解决了吗？
