### ISSUE TITLE
这书是机翻的吧

### ISSUE THREAD

**Issue by loveship00** [rootsongjc/kubernetes-handbook#371]
话读不通啊！

**Comment by rootsongjc** [comment]
@loveship00 请问哪篇读不通，我可以修正下。

**Comment by loveship00** [comment]
云原生不是关于在容器中运行应用程序。当Netflix率先推出云原生基础设施时，几乎所有应用程序都部署了虚拟机映像，而不是容器。打包应用程序的方式并不意味着您将拥有自治系统的可扩展性和优势。即使您的应用程序是通过持续集成和持续交付渠道自动构建和部署的，这并不意味着您可以从可以补充API驱动部署的基础设施中受益。

**Comment by rootsongjc** [comment]
@loveship00 Cloud Native Infrastructure 的中文版已经上市了，你可以直接购买或者在网上下载其英文原版（可免费下载），https://jimmysong.io/kubernetes-handbook/cloud-native/cloud-native-philosophy.html 这篇文章是我在阅读该书的时候随手翻译的，仅供参考。
