### ISSUE TITLE
https://labs.play-with-k8s.com/  用github账号登录后，出现500

### ISSUE THREAD

**Issue by nizaibeifang** [rootsongjc/kubernetes-handbook#376]
登陆Play with Kubernetes，点击【登陆】-【开始】即可开始你的Kubernetes之旅！

![image](https://user-images.githubusercontent.com/38808039/64105263-77d29500-cda8-11e9-9686-c36f2b90f6b7.png)

**Comment by rootsongjc** [comment]
我刚试了下确实是如你所说的，可能是该网站本身的技术问题。

**Comment by rootsongjc** [comment]
经测试，该网站已回复访问。https://labs.play-with-k8s.com/
