### ISSUE TITLE
kube-apiserver.service running error ：code=exited, status=203/EXEC

### ISSUE THREAD

**Issue by beyondli** [rootsongjc/kubernetes-handbook#38]
**kube-apiserver.service running error ：code=exited, status=203/EXEC**

when I start apiserver, it failed directly with status=203, since configure of apiserver isnot so complicated ,where maybe faults reasons.........

in message files， details follows：

````
Aug 22 11:11:04 k8server systemd: Starting Kubernetes API Service...
Aug 22 11:11:04 k8server systemd: Failed at step EXEC spawning /usr/bin/kube-apiserver: Exec format error
Aug 22 11:11:04 k8server systemd: kube-apiserver.service: main process exited, code=exited, status=203/EXEC
Aug 22 11:11:04 k8server systemd: Failed to start Kubernetes API Service.
Aug 22 11:11:04 k8server systemd: Unit kube-apiserver.service entered failed state.
Aug 22 11:11:04 k8server systemd: kube-apiserver.service failed.
Aug 22 11:11:04 k8server systemd: kube-apiserver.service holdoff time over, scheduling restart.
```

**Comment by beyondli** [comment]
my apiserver version is 1.7.3， I just followed your pdf file to configure these config files. since your version is 1.6.0,  Do these config files may not compatible with 1.7.3???

**Comment by rootsongjc** [comment]
Check your `kube-apiserver` binary file type whether compatible for your OS.

**Comment by beyondli** [comment]
hi,
 I have reinstall 1.6 version downloaded from the link doc provided(my OS is centos7 also ) just like doc described and I also copy apiservice config kube-apiservice from your wet site those files stored and modified some to fit my cluster(3 nodes only), however error still occues........

-----
[root@k8server kubernetes]# systemctl status kube-apiserver -l
● kube-apiserver.service - Kubernetes API Service
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Wed 2017-08-23 10:49:23 CST; 6s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 9715 ExecStart=/root/local/bin/kube-apiserver $KUBE_LOGTOSTDERR $KUBE_LOG_LEVEL $KUBE_ETCD_SERVERS $KUBE_API_ADDRESS $KUBE_API_PORT $KUBELET_PORT $KUBE_ALLOW_PRIV $KUBE_SERVICE_ADDRESSES $KUBE_ADMISSION_CONTROL $KUBE_API_ARGS (code=exited, status=203/EXEC)
 Main PID: 9715 (code=exited, status=203/EXEC)

Aug 23 10:49:22 k8server systemd[1]: kube-apiserver.service: main process exited, code=exited, status=203/EXEC
Aug 23 10:49:22 k8server systemd[1]: Failed to start Kubernetes API Service.
Aug 23 10:49:22 k8server systemd[1]: Unit kube-apiserver.service entered failed state.
Aug 23 10:49:22 k8server systemd[1]: kube-apiserver.service failed.
Aug 23 10:49:23 k8server systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
Aug 23 10:49:23 k8server systemd[1]: start request repeated too quickly for kube-apiserver.service
Aug 23 10:49:23 k8server systemd[1]: Failed to start Kubernetes API Service.
Aug 23 10:49:23 k8server systemd[1]: Unit kube-apiserver.service entered failed state.
----------------
too frustrated for about one week of this troubleshoot..........big sigh........please give me some ways try to resolved.... thanks!!

**Comment by beyondli** [comment]
@rootsongjc , hi resolved!!
I again download 1.6.0 and test again ,this time is OK,  my GOD!!
-----
[root@k8server kubernetes]# systemctl status kube-apiserver
● kube-apiserver.service - Kubernetes API Service
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-08-23 11:26:38 CST; 17s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 11185 (kube-apiserver)
   CGroup: /system.slice/kube-apiserver.service
           └─11185 /root/local/bin/kube-apiserver --logtostderr=true --v=0 --etcd-servers=https://10.6.128.100:...

---------
however I found 1.7.3 have more difference input parameters with 1.6. apiservice for example:

1:--port  has been deleted
2:--v has been deleted, only have --version
3:--logtostderr has been deleted!!
and many more para have been changed or obsoleted.......

so if next time you updata your doc to 1.7.3 or more higher version, I think you have to work to test and test an test.....  :)

however , thank you for you doc ,I can follow that to create my cluster easily and save my time......
