### ISSUE TITLE
master部署文档的问题，可能会造成无法使用hpa功能

### ISSUE THREAD

**Issue by Jacky-fe** [rootsongjc/kubernetes-handbook#39]
建议把flanneld的部署单独放在一个章节里，并且说明master和node都要安装
原因如下：
由于把flanneld的部署放到了node部署里，所以我安装master的时没有部署flanneld
而且我的master是单独部署的，并没有在同一台机器上既是master又是node
最后导致controller-manager无法访问heapster，最终无法实现弹性伸缩（hpa）

问题是很简单，不过我定位这个问题花了差不多一天时间。因为网上的解决方案都和我遇到的情况不一样
后来我了解到controller-manager是负责hpa的，所以查看controller-manager的日志推断出这个原因

**Comment by rootsongjc** [comment]
感谢您的建议，我将适时增加单独的flannel安装章节。
