### ISSUE TITLE
calicoctl使用前要配置环境变量

### ISSUE THREAD

**Issue by hzliangbin** [rootsongjc/kubernetes-handbook#396]
## 环境
**版本和配置信息**

- kubernetes版本：1.16
- docker版本：19.03
- 网络插件：calico
- 存储类型：nfs

## 操作
执行:
`calicoctl  get  node`

报错:
`Failed to create Calico API client: no etcd endpoints specified`

原因:
calicoctl命令使用前应配置环境变量,否则报错

文档链接
https://jimmysong.io/kubernetes-handbook/concepts/calico.html

calico说明
https://docs.projectcalico.org/getting-started/calicoctl/configure/kdd

**Comment by rootsongjc** [comment]
@hzliangbin 请直接提交 PR 修改。谢谢。
