### ISSUE TITLE
《06-部署node节点.md》语法错误

### ISSUE THREAD

**Issue by l-yb** [rootsongjc/kubernetes-handbook#4]
mk /kube-centos/network/config "{"Network":"172.30.0.0/16","SubnetLen":24,"Backend":{"Type":"vxlan"}}"

应该写成 
mk /kube-centos/network/config '{"Network":"172.30.0.0/16","SubnetLen":24,"Backend":{"Type":"vxlan"}}'

或者
set /kube-centos/network/config '{"Network":"172.30.0.0/16","SubnetLen":24,"Backend":{"Type":"vxlan"}}'

还有一点，示例要提示下是私有仓库：
sz-pg-oam-docker-hub-001.tendcloud.com/library/nginx:1.9

不然又得坑。。。。。

**Comment by rootsongjc** [comment]
多谢提醒，已修正。
