### ISSUE TITLE
Gitbook 改版

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/kubernetes-handbook#414]
本书自开源之日起，就一直使用的 Gitbook v1 自行构建的，而 v1 的 Gitbook 以在界面和用户体验上已经比较过时了，构建速度还特别慢，[新版的 Gitbook](https://www.gitbook.com/) 看上去会更加清爽现代，不知大家对此怎么看？是否有必要更新成新版的 Gitbook 样式？

**Comment by gladmo** [comment]
我也在找 新版本的 Gitbook ，好像已经商业商没有开源。

现在在用Rust社区的 [mdbook](https://github.com/rust-lang/mdBook)，挺好用的，就是感觉界面还是Gitbook的好看。

**Comment by rootsongjc** [comment]
新版的gitbook没有来源，mdbook感觉还是太简单了，目前看来可以用gitbook托管然后设置自定义域名。

**Comment by Wheeeeeeeeels** [comment]
ok

**Comment by yusiwen** [comment]
@rootsongjc 用3.2.3的gitbook build项目失败了，是不是只能用V1来make？

**Comment by rootsongjc** [comment]
暂时不打算迁移到新版本的 Gitbook 了，还用 v1 版本编译，关闭该 issue。

**Comment by yusiwen** [comment]
@rootsongjc  V1版本的话，是不是Node.js有版本要求？我用Node v12报错，估计是gitbook v1太老了？你编译文档用的node 版本是多少的？

**Comment by rootsongjc** [comment]
我目前使用的 nodejs 版本是v12.18.4，另外我还做了个 docker 镜像，可以使用 docker 来编译本书。

**Comment by yusiwen** [comment]
@rootsongjc 好的，我再试试，非常感谢
