### ISSUE TITLE
User "system:serviceaccount:kube-system:default" cannot list replicationcontrollers in the namespace "default". (get replicationcontrollers)

### ISSUE THREAD

**Issue by swy1314** [rootsongjc/kubernetes-handbook#42]
这个问题是因为没有给default服务帐号授权，但是文档中的dashboard-rbac.yaml也没有对default服务帐号授权，所以需要在subjects下增加一个，如：
- kind: ServiceAccount
  name: dashboard
  namespace: kube-system
**- kind: ServiceAccount
  name: default
  namespace: kube-system**

**Comment by rootsongjc** [comment]
我在部署时候未发现这个问题，因此标记为`fuzzy`。
