### ISSUE TITLE
jimmysong.io Unknown host

### ISSUE THREAD

**Issue by zero47** [rootsongjc/kubernetes-handbook#421]
## 环境

**版本和配置信息**

- kubernetes版本：
- docker版本：
- 网络插件：
- 存储类型：

## 操作
访问 https://jimmysong.io/kubernetes-handbook 报 526

**导致该问题的操作或现象**

## 日志

**日志或报错信息**

**Comment by rootsongjc** [comment]
因为证书错误，现已恢复。
