### ISSUE TITLE
4.1.5-部署master节点 错误问题

### ISSUE THREAD

**Issue by 3792274** [rootsongjc/kubernetes-handbook#44]
文章最后原文：
`
$ kubectl get componentstatuses
`

应该改成:
`kubectl --server=10.20.1.241:8080  get componentstatuses`

否则会弹出：
`The connection to the server localhost:8080 was refused - did you specify the right host or port?`

**Comment by rootsongjc** [comment]
因为我们在 4.1.2 创建kubeconfig文件中已经配置kubernetes的context，在master节点上生成了`$HOME/.kube/config` 文件，所以此处应该不需要执行API server的地址了。

**Comment by 3792274** [comment]
谢谢，我还是不太明白，在master节点上生成了$HOME/.kube/config 文件的过程，是那句命令生成的呢？
在`http://kubernetes.kansea.com/docs/user-guide/sharing-clusters/`中写的，是通过`cluster/kube-up.sh`产生的，可是没发现文档调用过这个

**Comment by rootsongjc** [comment]
当配置好了 context 之后只要执行了 kubectl 命令就会自动创建 `$HOME/.kube/config` 文件。

**Comment by 3792274** [comment]
`谢谢！我有重头试了下，当执行：`kubectl get componentstatuses`  还是没有生成 `/root/.kube/config` 文件,最后发现，`4.1.4-安装kubectl命令行工具` 中 `创建 kubectl kubeconfig 文件`需要执行一遍，尤其最后一句`kubectl config use-context kubernetes` && 生成的 `kubeconfig 被保存到 ~/.kube/config 文件`
文件解决，谢谢！
