### ISSUE TITLE
翻译错误：https://www.kubernetes.org.cn/deployment 中“直邮”应该为“只有”

### ISSUE THREAD

**Issue by web-no-stop** [rootsongjc/kubernetes-handbook#451]
## 环境

**版本和配置信息**

- kubernetes版本：
- docker版本：
- 网络插件：
- 存储类型：

## 操作

**导致该问题的操作或现象**

## 日志

**日志或报错信息**

**Comment by rootsongjc** [comment]
你好，在 https://jimmysong.io/kubernetes-handbook 中并没有“直邮”二字，你说的 https://www.kubernetes.org.cn/deployment  这个网页跟本书也没有直接关联。

**Comment by rootsongjc** [comment]
所提 issue 非本书中的内容，关闭。
