### ISSUE TITLE
跪求编译一个epub的版本

### ISSUE THREAD

**Issue by goace** [rootsongjc/kubernetes-handbook#452]
不知作者能否帮忙编译一个epub的版本放到release里，这样方便放在kindle里阅读，万分感谢

**Comment by rootsongjc** [comment]
你可以通过 gitbook 自行编译 epub 版本，注意有 gif 图片的问题，可能编译失败，例如"cloud-native/cloud-native-local-quick-start.md"文件中的，可以删除该图片或者转换格式后重新编译。

**Comment by rootsongjc** [comment]
该问题已解决，release 里已包含 epub 格式。
