### ISSUE TITLE
pulumi 不是一个云原生的编程语言

### ISSUE THREAD

**Issue by Svtter** [rootsongjc/kubernetes-handbook#453]
https://github.com/rootsongjc/kubernetes-handbook/blob/master/cloud-native/cloud-native-programming-language-pulumi.md

您好，感谢您的书籍。

经过阅读 Plulumi 的官方文档，私以为 pulumi 不是一个云原生的编程语言，更像是用于构建 cloud infrastructure 的 DSL。

> Pulumi is an open source infrastructure as code tool for creating, deploying, and managing cloud infrastructure.

**Comment by rootsongjc** [comment]
你的说法没错，可以说 Pulumi 基于「基础设施即代码」理念开发的一种配置语言，可以说是一种云原生基础设施配置代码化语言，也是 DSL，与 Kusion 和 KCL 类似，参考阅读 [KCL：声明式的云原生配置策略语言](https://segmentfault.com/a/1190000040455559)。
