### ISSUE TITLE
编译成本地pdf或者epub时报错

### ISSUE THREAD

**Issue by crystal8946** [rootsongjc/kubernetes-handbook#459]
## 环境
WIN10
**导致该问题的操作或现象**
编译您其它两本书的时候都没有这个现象，唯独这本使用gitbook pdf或者gitbook epub命令时都会报错
## 日志
warn: "options" property is deprecated, use config.get(key) instead
warn: "options.generator" property is deprecated, use "output.name" instead
error: error while generating page "README.md":

Error: ENOENT: no such file or directory, open 'C:\Users\DINGSH~1\AppData\Local\Temp\tmp-28644sMPiniykirvg\35dd28a.svg?style=svg'
**日志或报错信息**

**Comment by crystal8946** [comment]
gitbook serve也可以成功没知识编译成epub不行

在README.MD中找到了“https://circleci.com/gh/rootsongjc/kubernetes-handbook/tree/master.svg?style=svg”把这整个段落都删掉尝试一下这个报错没了，但是报错

error: error while generating page "cloud-native/cloud-native-local-quick-start.md":

Error: read ECONNRESET

**Comment by rootsongjc** [comment]
gitbook 编译的时候无法处理 svg 格式内容，README.md 里的 svg 需要删除，另外编译的时候还需要翻墙，我不确定究竟要连接哪个URL ，但是翻墙后在我的电脑上编译只需要一分多钟就可以编译完成。不翻墙就是  `Error: read ECONNRESET` 这个报错。我今天编译了一个 epub 格式出来，你可以在 [Release 页面](https://github.com/rootsongjc/kubernetes-handbook/releases/tag/v20220301)下载。

**Comment by crystal8946** [comment]
> gitbook 编译的时候无法处理 svg 格式内容，README.md 里的 svg 需要删除，另外编译的时候还需要翻墙，我不确定究竟要连接哪个URL ，但是翻墙后在我的电脑上编译只需要一分多钟就可以编译完成。不翻墙就是 `Error: read ECONNRESET` 这个报错。我今天编译了一个 epub 格式出来，你可以在 [Release 页面](https://github.com/rootsongjc/kubernetes-handbook/releases/tag/v20220301)下载。

感谢大佬，如此说来可能是公司安全组策略搞的鬼，下次我在家里环境编译一下试试，再次感谢！

**Comment by rootsongjc** [comment]
@crystal8946 不用客气，不过 epub 和 pdf 格式对于表格的渲染都可能有问题，对于列数比较多，内容很长的表格可能会溢出，影响阅读体验，因此最好的阅读方式还是在线阅读。

**Comment by crystal8946** [comment]
> @crystal8946 不用客气，不过 epub 和 pdf 格式对于表格的渲染都可能有问题，对于列数比较多，内容很长的表格可能会溢出，影响阅读体验，因此最好的阅读方式还是在线阅读。

我已经在本地编译成了gitbook serve，不过我的电脑性能不是很好，每次打开serve都要3分多钟，编辑成epub主要是在电子书上学习~

**Comment by crystal8946** [comment]
换了个环境再次尝试编译，看来应该是我代理的问题，应该是某个地址被链路上某个节点给墙了，导致无法编译成功
Error: connect ETIMEDOUT 182.43.124.6:443

**Comment by crystal8946** [comment]
换了个环境再次尝试编译，看来应该是我代理的问题，应该是某个地址被链路上某个节点给墙了，导致无法编译成功

**Comment by rootsongjc** [comment]
一般就是这个问题，不过有的时候也不需要代理编译

**Comment by crystal8946** [comment]
- 再次感谢~
