### ISSUE TITLE
6.5.7 章节缺少说明

### ISSUE THREAD

**Issue by reply2future** [rootsongjc/kubernetes-handbook#467]
[具体位置](https://jimmysong.io/kubernetes-handbook/practice/manage-compute-resources-container.html#:~:text=%E4%B8%80%E8%88%AC%E6%9D%A5%E8%AF%B4%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%9C%89%E8%BF%99%E7%A7%8D%E7%B1%BB%E5%9E%8B%E7%9A%84%E6%B6%88%E6%81%AF%E8%80%8C%E5%A4%84%E4%BA%8E%20pending%20%E7%8A%B6%E6%80%81%EF%BC%8C%E6%82%A8%E5%8F%AF%E4%BB%A5%E5%B0%9D%E8%AF%95%E5%A6%82%E4%B8%8B%E5%87%A0%E4%BB%B6%E4%BA%8B%E6%83%85%EF%BC%9A)

![image](https://user-images.githubusercontent.com/6359152/163741255-d43b30d6-d75c-4e24-8c48-24f43ecb1e36.png)

**Comment by rootsongjc** [comment]
请参考[这篇官方文档](https://kubernetes.io/zh/docs/concepts/configuration/manage-resources-containers/#%E6%88%91%E7%9A%84-pod-%E5%A4%84%E4%BA%8E%E6%82%AC%E5%86%B3%E7%8A%B6%E6%80%81%E4%B8%94%E4%BA%8B%E4%BB%B6%E4%BF%A1%E6%81%AF%E6%98%BE%E7%A4%BA-failedscheduling)。
