### ISSUE TITLE
Ceph的块存储简称错误

### ISSUE THREAD

**Issue by firmament2008** [rootsongjc/kubernetes-handbook#476]
https://www.lanqiao.cn/library/kubernetes-handbook/practice/ceph
Ceph的块存储（Ceph RBD）
Ceph中的分布式块存储（Ceph RDB）
有2个名词  RBD RDB  到底哪个是正确的呢？

**Comment by rootsongjc** [comment]
在 [Ceph](https://jimmysong.io/kubernetes-handbook/practice/using-ceph-for-persistent-storage.html) 这篇文章中的 RBD 指的是 RADOS Block Device。参考：https://www.techtarget.com/searchstorage/definition/RADOS-Block-Device-RBD
