### ISSUE TITLE
关于06-部署node节点的疑问

### ISSUE THREAD

**Issue by trockxi** [rootsongjc/kubernetes-handbook#5]
在最开始的检测中ls /etc/kubernetes/发现缺少kubelet和proxy，查看了前面的步骤也未发现生成这两个文件的地方，然后继续向下，在“配置Docker”后面的步骤感觉是跳跃的，最后在etcdctl --endpoints=${ETCD_ENDPOINTS} \
>   --ca-file=/etc/kubernetes/ssl/ca.pem \
>   --cert-file=/etc/kubernetes/ssl/kubernetes.pem \
>   --key-file=/etc/kubernetes/ssl/kubernetes-key.pem \
>   ls /kube-centos/network/subnets
2017-05-12 17:03:32.679837 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
提示下面错误
Error:  100: Key not found (/kube-centos/network/subnets) [8]
找不到问题所在，故来请教，这第06步的具体顺序步骤，因为有些地方不懂，不是顺序步骤无法进行下去。

**Comment by rootsongjc** [comment]
步骤顺序是这样的
- 首先配置flannel
- 云行flanneld的`./mk-docker-opts.sh -i`脚本
- 设置docker0网桥的IP地址
- 启动docker
- 启动flanneld

这之后flannel就会自动向ectd中注册subnet。
谢谢提醒，我修改下该文章中的步骤顺序。
