### ISSUE TITLE
RHEL6.5的配置咨询

### ISSUE THREAD

**Issue by beyondli** [rootsongjc/kubernetes-handbook#52]
我在RHEL6.5下配置，发现系统没有systemctl命令，只能采用service貌似，如果这样是否有可以参考的`etcd.service`等其他类似service的配置文件可以参考？
谢谢！！

**Comment by rootsongjc** [comment]
RHEL6.5这个操作系统的版本有点低，官方推荐使用CentOS7版本，见https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

**Comment by beyondli** [comment]
问下目前业内大家一般都是用哪个系统多些？因为我们目前项目都是RHEL6.5，老板让在这个系统上验证，不知道是劝说老板换系统，还是再研究这个老的版本上的所有适配工作了。。。。

**Comment by beyondli** [comment]
考虑下至少RHEL7了，没有systemctl要命了，service都不知道该咋整了

**Comment by rootsongjc** [comment]
一般都使用RHEL7了，对于6.5的系统我没有验证过。
