### ISSUE TITLE
NodePort无法访问

### ISSUE THREAD

**Issue by sxauyhz** [rootsongjc/kubernetes-handbook#6]
首先感谢文档，在06-部署node节点.md中都部署OK了，就是最后一步浏览器直接访问node:nodePort打不开。测试端口不通。
我排查如下：1，我的nodePort是30001端口，浏览器直接访问（telnet）不通，但是我把该服务关闭，启动一个httpd监听到该端口测试是可以访问。
                     2，其中在node节点本地直接访问是OK的，即curl 本地物理网卡地址:30001 ；node节点本地curl service_ip:80也是OK的
请指点一下问题出在哪里？

**Comment by rootsongjc** [comment]
你所说的“本地”跟你的集群是什么关系？是在同一个网络环境下吗？

**Comment by sxauyhz** [comment]
感谢，🙏，
是iptables的问题，在node上执行一下该命令就OK了：
sudo iptables -P FORWARD ACCEPT
