### ISSUE TITLE
Error from server (BadRequest): Upgrade request required

### ISSUE THREAD

**Issue by yin32167** [rootsongjc/kubernetes-handbook#60]
根据你的教程, 我成功的部署了k8s, 另外我加了nginx代理两台master, 一切都挺正常, 但在执行kubectl exec 命令的时候, 出现错误"Error from server (BadRequest): Upgrade request required", 查了资料, 说是要nginx支持http2, 后来这个我也配置了, 但还是报同样的错误, 请教一下, 这种错误怎么解决了?

**Comment by rootsongjc** [comment]
你说的这个问题有详细日志信息吗？

**Comment by yin32167** [comment]
@rootsongjc 后来发现nginx需要配置 

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";

可能是需要支持websocket
