### ISSUE TITLE
集群管理的 "certificatesigningrequests" 具体有哪些用途？

### ISSUE THREAD

**Issue by JinsYin** [rootsongjc/kubernetes-handbook#61]
[管理集群中的TLS](https://jimmysong.io/kubernetes-handbook/guide/managing-tls-in-a-cluster.html) 中提到了如何 create/approve/deny csr，但我还是不太明白该如何使用它，它的用途在哪里呢？

**Comment by rootsongjc** [comment]
这个是新主机向master请求加入集群的时候发送的认证请求，因为我们安装的时候使用了bootstrap，所以可以不approve，就自动加入到集群中。

**Comment by JinsYin** [comment]
Thanks。基本上理解了，我对 kubeadm 分析了一下，发现集群自动创建的 csr 信息和 kubelet 引用的 kubelet.conf 文件中的信息确实是一致的。
