### ISSUE TITLE
kubernetes master节点的高可用

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/kubernetes-handbook#63]
我们在安装 kubernetes 集群之初并没有为 master 节点上的三个进程 kube-apiserver、kube-controller-manager 和 kube-scheduler 做高可用，都部署到了同一台机器上了，考虑使用 haproxy 为 master 节点上的这三个组件做高可用。

**Comment by gjmzj** [comment]
使用 haproxy和keepalived做master节点的高可用，可以参考本人项目[https://github.com/gjmzj/kubeasz](https://github.com/gjmzj/kubeasz)
