### ISSUE TITLE
解决Ceph RBD 做持久化存储创建MySQL集群遇到的问题

### ISSUE THREAD

**Issue by zhangchenchen** [rootsongjc/kubernetes-handbook#73]
利用Ceph RBD 做持久化存储创建MySQL集群时，采用Dynamic Volume Provisioning方式（即storageclass方式），kube-controller-manager会报错“rbd not found”，经过试验与搜索后发现该问题的解决方案并将相关内容记录到对应markdown中，已pull request。

**Comment by rootsongjc** [comment]
但是我的集群并不是使用kubeadm安装的，kube-controller-manager直接部署在物理机上。

**Comment by yangshuai93** [comment]
@zhangchenchen 
 在kube-controller-manager image 里 安装ceph client .
应该可以。

**Comment by rootsongjc** [comment]
那对于使用二进制文件在物理机上直接装的kube-controller-manager呢？如何解决？

**Comment by yangshuai93** [comment]
物理机上有ceph client 应该就可以了
这个没试过

**Comment by zhangchenchen** [comment]
我理解的Dynamic Volume Provisioning是这样一个过程：
1，volume provisioning: 就是k8s（严格说来是kube-controller-manager）与ceph对接验证，并根据pvc创建对应大小的image。
2，volume attach:这个过程就是调用rbd map，将volume attach到host上。
这两个过程都需要ceph 模块的参与。第一个过程需要kube-controller-manager所在的环境要有ceph client，第二个过程需要对应host有ceph client 。
按理说物理机上直接装的kube-controller-manager应该在物理机上直接装ceph-common就够了，我也没有实际验证过（如果有时间我会实践一下）。
我看了一下lz说的日志，报的不是rbd $PATH not found 的错误，而是
```bash
rbd: create volume failed, err: failed to create rbd image: fork/exec /usr/bin/rbd: invalid argument, command output:
``` 
所以，只是猜测一下：会不会是ceph 验证问题，或者ceph client 版本问题

**Comment by rootsongjc** [comment]
@zhangchenchen 很有可能是与ceph得验证问题，可是直接在物理机上直接执行rbd创建volume是正常的。现在的这种报错信息没有输出命令的全部字段，没法排查问题。

**Comment by zhangchenchen** [comment]
恩，可以先尝试静态PV,PVC的方式，看看能不能mount到pod上，如果可以，那么ceph-secret是没有问题的。那么问题就是storage-class的配置。

**Comment by wadefelix** [comment]
是不是参考这个 https://github.com/kubernetes/kubernetes/issues/38923#issuecomment-315255075
