### ISSUE TITLE
关于 06-部署node节点 的问题： node 上访问service ip失败 

### ISSUE THREAD

**Issue by eagleyinfz** [rootsongjc/kubernetes-handbook#8]
[root@node1 ~]# curl 10.254.242.36
curl: (7) Failed connect to 10.254.242.36:80; No route to host
找不出问题，故来请教

**Comment by rootsongjc** [comment]
请先查看kubelet和kube-proxy的日志信息，并提供更多日志信息才能便于查看问题。

**Comment by rootsongjc** [comment]
@eagleyinfz 有进展吗？

**Comment by eagleyinfz** [comment]
@rootsongjc , 我发现我之前是在master节点 请求部署的service 报上面的错误，node节点请求部署的service是成功的， master节点并没有作为node提供服务，是不是可以理解为master节点访问不到集群内service？请指教，多谢！！

**Comment by rootsongjc** [comment]
master节点如果想访问到kubernetes的服务，必须要安装kube-proxy，可能还需要flannel吧。否则无法路由到ClusterIP的。

**Comment by eagleyinfz** [comment]
@rootsongjc get 了， 确实是这个样子的。super thanks

**Comment by BigbigY** [comment]
我也遇到同样的问题，以下是kubelet日志
```
Apr 03 14:33:45 hz-k8s-cluster-n02 kubelet[26754]: E0403 14:33:45.618768   26754 fs.go:418] Stat fs failed. Error: no such file or directory
Apr 03 14:33:55 hz-k8s-cluster-n02 kubelet[26754]: E0403 14:33:55.782571   26754 fs.go:418] Stat fs failed. Error: no such file or directory
Apr 03 14:34:08 hz-k8s-cluster-n02 kubelet[26754]: E0403 14:34:08.559176   26754 fs.go:418] Stat fs failed. Error: no such file or directory
```

**Comment by rootsongjc** [comment]
@BigbigY 你创建了 `/var/lib/kubelet` 目录了吗？

**Comment by BigbigY** [comment]
创建了 @rootsongjc
