### ISSUE TITLE
kubelet --cgroup-driver 的配置问题

### ISSUE THREAD

**Issue by louting** [rootsongjc/kubernetes-handbook#81]
## 建议

原文：4.1.6 部署node节点
--cgroup-driver 配置成 systemd，不要使用cgroup，否则在 CentOS 系统中 kubelet 讲启动失败。

建议： 这个最好还是根据实际情况来，如果docker启动参数使用的是cgroup，这个地方配置成systemd就会造成kubelet启动失败。另外这句里面有个错字～～

第一次提 issue ～ 可能写的有问题哈～～ 

谢谢大神的教程。

**Comment by rootsongjc** [comment]
多谢您的建议。已经改正。
