### ISSUE TITLE
configmap更新配置，在pod里生效问题

### ISSUE THREAD

**Issue by heshengkai** [rootsongjc/kubernetes-handbook#84]
宋老师，请教个configmap的问题，我pod里运行的是tomcat,我把项目中的一个配置文件放到了configmap中，我更新了configmap,如何保证在不重建pod的情况下，pod里tomcat运行的项目加载新配置生效？

**Comment by rootsongjc** [comment]
tomcat是能够热加载配置文件吗？configmap更新后，挂载到pod中的volume会自动更新，不过需要一段时间，大概10秒钟的样子。

**Comment by heshengkai** [comment]
搜了一下，tomcat支持热加载和和热部署，我再测试一下。

**Comment by gjmzj** [comment]
@heshengkai 这篇文章[https://www.kubernetes.org.cn/3138.html](https://www.kubernetes.org.cn/3138.html) 看下是否有帮助

**Comment by rootsongjc** [comment]
@gjmzj 这篇文章就是我写的，见kubernetes-handbook中的https://jimmysong.io/kubernetes-handbook/concepts/configmap-hot-update.html

**Comment by TheHati** [comment]
@rootsongjc  宋老师您好，请问一下如何在不覆盖源目录中文件的同时，对配置文件进行热更新呢？比如将/etc/nginx/nginx.conf作为配置文件，只能通过符号链接吗？谢谢
