### ISSUE TITLE
1.6.3 升级 1.7.6 后cluster-info  服务url地址错误

### ISSUE THREAD

**Issue by qinwei1314ai** [rootsongjc/kubernetes-handbook#86]
## 环境
CentOS Linux release 7.2.1511 (Core) 
4.12.6-1.el7.elrepo.x86_64
docker 1.12.6

**版本和配置信息**

- kubernetes版本：1.7.6
- docker版本： 1.12.6
- 网络插件：flanneld  host-gw
- 存储类型：overlay2

## 操作
1.6.3 替换二进制文件强制升级到1.7.6 
**导致该问题的操作或现象**
升级后以前pod可以正常运行，服务正常。但查看cluster-info后发现 安装的服务的url地址不对：proxy的位置发生了改变，之前是：
https://10.100.146.112:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
现在变成了：
https://10.100.146.112:6443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy
输入错误的url不能访问到对应的业务，输入之前的url可以正常访问
## 日志
暂时未发现错误日志
**日志或报错信息**

**Comment by rootsongjc** [comment]
@qinwei1314ai qin 这个问题我也遇到了，我暂时使用非安全端口8080来访问的，对于https来访问会出现页面加载不完整的问题。
