### ISSUE TITLE
将flannel的网络模式由vxlan改为host-gw,容器跨主机ping不通了

### ISSUE THREAD

**Issue by heshengkai** [rootsongjc/kubernetes-handbook#87]
@rootsongjc 宋老师，我之前的flannel设置的模式是vxlan,容器之间的通信正常，但是改成host-gw，网络之间就不通了，请指教一下。下面是我改成host-gw后，服务器上路由情况

![Uploading QQ图片20171221224151.png…]()
![Uploading QQ图片20171221224217.png…]()

**Comment by rootsongjc** [comment]
@heshengkai 你的图片无法正常显示。另外，你没有交代安装环境，是在公有云、物理机还是什么网络环境下安装的。host-gw只支持二层互通的网络。

**Comment by heshengkai** [comment]
@rootsongjc 宋老师，我是在公有云上安装的，我今天又查了一下，是公有云上网络环境导致的。

**Comment by rootsongjc** [comment]
@heshengkai 你用的是什么云？另外用的是flannel的host-gw网络吗？

**Comment by heshengkai** [comment]
@rootsongjc 是新致云，www.newtouch.com;之前一直用的是flannel的vxlan，最近想在测试环境中测试一下host-gw莫模式

**Comment by rootsongjc** [comment]
@heshengkai 那你得联系下新致云了，看看他们的网络是否支持host-gw模式。

**Comment by heshengkai** [comment]
@rootsongjc 嗯，我和新致云那边核实一下

**Comment by jeffrey4l** [comment]
> @heshengkai 你的图片无法正常显示。另外，你没有交代安装环境，是在公有云、物理机还是什么网络环境下安装的。host-gw只支持二层互通的网络。

@rootsongjc  hi, 
二层网络互通是什么意思? 不支持 service? 那 非 overlay 网络有支持 service 的么?

**Comment by rootsongjc** [comment]
二层网络互通就是说所有的节点都在一个网络平面里。
