### ISSUE TITLE
如果master不是node节点的时候，安装dashboard的时候会报错Error: 'dial tcp 172.18.0.3:8443: getsockopt: no route to host'

### ISSUE THREAD

**Issue by zm274310577** [rootsongjc/kubernetes-handbook#92]
## 环境
我安装的是kubernetes1.8.5，基本都是照着kubernetes-handbook操作下来的，但是到安装dashboard的时候遇到了点问题，我使用的是dashboard1.8.0版本，在写配置文件的时候，需要配置`--apiserver-host=http://172.17.14.112:8080`，否则安装失败

我在vsphere上创建了4台Centos7的虚拟机安装，分别是：
```
主机名    ip
bigdata    172.17.14.112
slave1      172.17.14.113
slave2      172.17.14.114
server       172.17.14.10
```
其中bigdata是计划做master的，slave1和slave2是node节点，server是harbor服务器

- kubernetes版本：
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- docker版本：
```
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:35:47 2017
 OS/Arch:      linux/amd64
Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:45:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
- 网络插件：
- 存储类型：

## 操作
一。我把master和两个node安装好以后，测试nginx，没有问题，说明集群是没有问题的（我一直tail /var/log/message，3个节点都没有报错）
但是下面测试nginx的时候和handbook有点不一样。
```bash
[root@bigdata ~]# kubectl describe svc example-service
Name:                     example-service
Namespace:                default
Labels:                   run=load-balancer-example
Annotations:              <none>
Selector:                 run=load-balancer-example
Type:                     NodePort
IP:                       10.254.23.194
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  31011/TCP
Endpoints:                172.18.0.2:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```
handbook是curl的10.254.23.194地址，但是我的不同，我curl 172.18.0.2:80可以正常出结果

二。然后我使用kubectl create kubernetes-dashboard.yaml进行dashboard的安装，安装没有问题，提示安装到了slave2节点上（目前我的master没有作为node节点使用）
通过下面的命令查看都是正常的
```kubectl get deployment kubernetes-dashboard --namespace=kube-system
NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kubernetes-dashboard   1         1         1            1           23m
kubectl get deployment  --namespace=kube-system
NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kubernetes-dashboard   1         1         1            1           23m
kubectl get --namespace kube-system pods
NAME                                   READY     STATUS    RESTARTS   AGE
kubernetes-dashboard-85b79bfb8-xg6xr   1/1       Running   0          23m
```
三。但是在浏览器中输入：主节点ip:8080/ui会报错
```
Error: 'dial tcp 172.18.0.3:8443: getsockopt: no route to host'
Trying to reach: 'https://172.18.0.3:8443/'
我的docker的地址是172.18段
5: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:1b:50:cb:e1 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:1bff:fe50:cbe1/64 scope link 
       valid_lft forever preferred_lft forever
```
四。但是如果我把master也安装为node节点（这时master即是主节点又是从节点），然后再安装dashboard，就会安装到master节点，这时候访问8080可以正常打开了。

**导致该问题的操作或现象**

我感觉这个dashboard作为kubernetes的插件，是不是必须要安装到master节点。
但是，我又感觉这样有点不妥当，因为通常来说，主节点不会同时设置为node节点的。但是这种情况又不能使用了。
求大神支招：
1. 是不是只能把master同时设置为node，然后dashboard安装在master上（但是这种情况，master做HA怎么办？）
2. 是不是有相应的配置，可以把dashboard配置到其他节点，master只做主节点使用。（目前我在网上没有找到）
## 日志

**日志或报错信息**

**Comment by rootsongjc** [comment]
## 问题

dashboard1.8.0版本默认应该是开启了https访问，所以你要使用https协议来访问，访问时需要提供token或者kubeconfig作为验证，你使用的8080端口应该是访问不了dashboard的。

## 解决方案

1. 你可以使用**nodePort**的方式来暴露dashboard服务，使用https访问。
2. 使用Ingress来代理dashboard服务
3. master做HA的话还需要使用VIP，创建证书的时候还要加入VIP的IP

**Comment by zm274310577** [comment]
@rootsongjc 宋老师，我的dashboard是可以通过8080访问的。这个是正常的。
其实简单点我的问题是，如果我的master不作为node使用的话，dashboard安装的时候会分配到某个node上，这时通过masterIP:8080是不可以访问的。如果我把master配置为node使用的话，dashboard会被分配到master节点上(当然我不确定一定会分配到master这个node)，这时可以通过masterIP:8080访问。
我有两点比较纠结：
1. 我可以接受dashboard运行在master，但是觉得把master配置node来使用不妥当，因为可能会有其他的pod被分配到master，这样会加大master的压力，但是不把master作为node使用，dashboard配置上不能访问，nodePort方式我也试了，不能使用
`[root@bigdata ~]# kubectl get svc kubernetes-dashboard --namespace=kube-system
NAME                   TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
kubernetes-dashboard   NodePort   10.254.160.183   <none>        443:30854/TCP   21h`
https://masterIP:30854打不开网页
2. 我看网上说的，dashboard没有任何的限制的。就是说，我通过masterIP:8080可以任意访问的。dashboard可以限制为常规的必须通过账号密码才能使用吗，通过什么方式可以配置。

**Comment by rootsongjc** [comment]
@zm274310577 你的master是使用kubectl proxy的方式运行的还是通过`nodePort`方式运行的，现在的情况怎样？

**Comment by PhoenixAD** [comment]
@zm274310577 
我有个类似的问题，局域网中一台master 三台node主机，一切运行正常，我在master（通过ssh控制）上执行
kubectl proxy --address='0.0.0.0' --port=8002 --accept-hosts='^.*$'
并在自己电脑上的浏览器访问 
masterIP:8002/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
返回：
Error: 'dial tcp 172.18.0.3:8443: getsockopt: no route to host'
Trying to reach: 'https://172.18.0.4:8443/'

172.18.0.4对应集群内node1的主机（非master结点）
想请问：1.如何强制把dashboard安装到master结点
               2.最终你的问题是怎么解决的呢

**Comment by zm274310577** [comment]
@PhoenixAD 如我问题所说的，如果我的master同时也是node，则自动会把dashboard安装到master这个node上(我安装是两三次都是这样的，不会安装到其他的node上)，这时不会报错。如果master不配置为node，则安装到某个node上，这时会报错。
我记得群里有个大神说，在kubernetes1.8.5这个版本（具体从哪个版本开始记不清了，隐约记得和1.8.5比较近）访问非master上安装的dashboard需要通过认证的方式访问，但这种访问我目前还没有试过。

**Comment by PhoenixAD** [comment]
@zm274310577 
我的集群master同时也是node，但只有集群中只有master（其他node尚未加入）时候dashboard才会部署到master，否则总是部署到其他node，就出现和你一样的问题。

**Comment by motecshine** [comment]
ping @rootsongjc  确实是这样的 ，如果master 节点 不做NODE节点，那dashboard 会装到 node上，就会出现类似的问题 
`error: 'dial tcp 172.17.0.3:9090: getsockopt: no route to host'
Trying to reach: 'http://172.17.0.3:9090/'`
宋老师有解决的方式么

**Comment by rootsongjc** [comment]
那么你的master节点有装 kube-proxy 吗？能够直接 curl 服务的 ClusterIP 加端口吗？

**Comment by motecshine** [comment]
有 kube-proxy
但是无法ping通 ClusterIP

**Comment by motecshine** [comment]
解决了kube-dns 没有安装

**Comment by Lemon-le** [comment]
同样的问题  先记录一下

**Comment by terryzwt** [comment]
这是我的步骤：
```
## 删除现有的dashboard
kubectl delete -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.2.0/aio/deploy/recommended.yaml

## 将node服务器设置为污点，这样dashboard就不会部署过去了，如果有更多参数，自行调整
kubectl taint nodes k8s-node1 note=void-dashboard:NoSchedule

## 重新部署dashboard
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.2.0/aio/deploy/recommended.yaml

## 取消node节点的污点设置
kubectl taint nodes k8s-node1 note=void-dashboard:NoSchedule-
```
