### ISSUE TITLE
安装promotheus时，有个系统镜像没有

### ISSUE THREAD

**Issue by qiangyin** [rootsongjc/kubernetes-handbook#99]
sz-pg-oam-docker-hub-001.tendcloud.com/library/centos:7.2.1511，这个镜像哪里下载啊

**Comment by rootsongjc** [comment]
这是我自己做的镜像，就是在官方的CentOS镜像的基础上做了点修改，你官方的CentOS docker镜像就行了。

**Comment by qiangyin** [comment]
感谢

**Comment by qiangyin** [comment]
放在时速云的grafana镜像index.tenxcloud.com/jimmy/grafana:4.2.0也没有了

**Comment by rootsongjc** [comment]
这个镜像在啊，亲测可以下载。
